import type { PortfolioEnvelope } from "@/types/content";

export const FALLBACK_ENVELOPE: PortfolioEnvelope = {
  schemaVersion: "1",
  siteKey: "velaarturo",
  publishedRevision: 1,
  generatedAt: "2026-09-04T00:00:00.000-05:00",
  data: {
    site: {
      name: "Arturo Vela",
      headline: "Diseño y construyo productos digitales que hacen simple lo complejo.",
      intro: "Ingeniero de sistemas y desarrollador web en Perú. Diseño interfaces, datos y servicios edge como un solo producto.",
      availability: "Abierto a conversar sobre productos, sistemas internos y colaboración técnica.",
      location: "Perú",
      bio: "Trabajo entre producto, interfaz e ingeniería. Me interesa entender primero el proceso real, reducir fricción y entregar sistemas que las personas puedan usar y mantener con confianza.",
      email: "velaarturo70@gmail.com",
      phone: "+51 963 653 154",
      cvUrl: "https://1drv.ms/b/s!AhTBs2k3EIAxjthfmoaQGB-VJxbvKA?e=jyDFsy",
      socials: [
        { label: "GitHub", url: "https://github.com/ArturoVela" },
        { label: "LinkedIn", url: "https://www.linkedin.com/in/arturo-vela-aa81242ba/" },
        { label: "Discord", url: "https://discord.gg/mnMkUXC5vK" },
      ],
      seo: {
        title: "Arturo Vela — Ingeniería de productos digitales",
        description: "Portafolio de Arturo Vela: aplicaciones web, sistemas internos, automatización e interfaces construidas desde Perú.",
        ogImage: "/og-card.png",
      },
    },
    services: [
      {
        id: "web-products",
        title: "Productos web",
        description: "Aplicaciones rápidas y accesibles, desde el flujo principal hasta el despliegue.",
        capabilities: ["React y TypeScript", "Diseño responsive", "Cloudflare Workers"],
      },
      {
        id: "internal-systems",
        title: "Sistemas internos",
        description: "Herramientas que ordenan información y reemplazan procesos manuales repetitivos.",
        capabilities: ["Modelado de datos", "Automatización", "Integraciones"],
      },
      {
        id: "ui-systems",
        title: "Sistemas de interfaz",
        description: "Lenguajes visuales consistentes que conectan productos de una misma familia.",
        capabilities: ["Chakra UI", "Tokens semánticos", "Accesibilidad"],
      },
    ],
    projects: [
      {
        id: "project-hub",
        slug: "hub",
        title: "Hub",
        excerpt: "39 herramientas cotidianas reunidas en una SPA local-first, rápida y modular.",
        body: "## El reto\n\nReunir utilidades de cálculo, texto, diseño, productividad y desarrollo sin convertir la portada en un paquete pesado.\n\n## La solución\n\nUna arquitectura React + Vite con carga diferida por herramienta. Los procesos sensibles permanecen en el navegador siempre que es posible; el Worker atiende solo las funciones que necesitan API o persistencia.\n\n## Enfoque\n\nEl catálogo funciona como fuente de verdad para rutas, búsqueda y relaciones. Favoritos, actividad reciente y preferencias viven localmente, mientras D1 guarda únicamente enlaces cortos y rankings.",
        category: "Producto personal",
        type: "Aplicación web",
        role: "Diseño y desarrollo integral",
        year: "2026",
        stack: ["React", "TypeScript", "Vite", "Chakra UI", "Cloudflare Workers", "D1"],
        outcomes: ["39 herramientas agrupadas en 11 categorías", "Procesamiento local para archivos y datos sensibles", "Carga bajo demanda por cada herramienta"],
        liveUrl: "https://hub.withered-hat-79c9.workers.dev",
        repoUrl: "https://github.com/ArturoVela/hub",
        featured: true,
        order: 1,
        seo: { description: "Hub reúne 39 herramientas web en una SPA local-first construida con React, Vite y Cloudflare Workers." },
      },
      {
        id: "project-un-ramito",
        slug: "un-ramito",
        title: "Un ramito",
        excerpt: "Una experiencia para crear y compartir ramos virtuales con dedicatorias privadas.",
        body: "## Una experiencia pequeña con privacidad real\n\nLa persona diseña un ramo, escribe una dedicatoria y comparte un enlace. La dedicatoria se cifra en el navegador antes de salir del dispositivo.\n\n## Arquitectura\n\nCloudflare D1 conserva solo el sobre cifrado durante 90 días. La clave viaja en el fragmento de la URL, que no se envía al servidor.",
        category: "Experiencia digital",
        type: "Aplicación web",
        role: "Producto, diseño y desarrollo",
        year: "2026",
        stack: ["React", "TypeScript", "Vite", "Chakra UI", "Web Crypto", "Cloudflare D1"],
        outcomes: ["Cifrado en el navegador", "Enlaces privados fáciles de compartir", "Caducidad automática de 90 días"],
        liveUrl: "https://un-ramito.workers.dev",
        repoUrl: "https://github.com/ArturoVela/flores",
        featured: true,
        order: 2,
        seo: { description: "Un ramito permite diseñar y compartir ramos virtuales con dedicatorias cifradas en el navegador." },
      },
      {
        id: "project-security-lab",
        slug: "security-lab",
        title: "Security Lab",
        excerpt: "Laboratorio privado para comparar cuatro generaciones de auditoría y sus entornos de prueba.",
        body: "## Aprender comparando\n\nEl laboratorio organiza cuatro versiones de una auditoría junto a sus ambientes de prueba. La matriz hace visibles los cambios entre una implementación original, una versión reforzada y reemplazos posteriores.\n\n## Límites claros\n\nLos módulos están diseñados para sistemas propios, académicos o con autorización expresa. El acceso es privado y las utilidades generales se separaron en Hub.",
        category: "Seguridad aplicada",
        type: "Laboratorio web privado",
        role: "Arquitectura y desarrollo",
        year: "2026",
        stack: ["Next.js", "React", "TypeScript", "Chakra UI", "Supabase"],
        outcomes: ["Comparación de cuatro generaciones", "Ocho módulos organizados en una matriz", "Separación de utilidades generales hacia Hub"],
        repoUrl: "https://github.com/ArturoVela/soteos-nextjs",
        featured: true,
        order: 3,
        seo: { description: "Laboratorio privado de Arturo Vela para comparar generaciones de auditoría y entornos de prueba." },
      },
      {
        id: "project-cana-wasky",
        slug: "cana-wasky",
        title: "Caña Wasky",
        excerpt: "Sistema en Excel para organizar ventas, inventario y reportes de un negocio gastronómico.",
        body: "## Contexto\n\nCaña Wasky necesitaba reunir el control comercial en una herramienta comprensible para la operación diaria.\n\n## Solución\n\nSe estructuró un sistema de ventas e inventario en Excel, con reportes automatizados y una interfaz pensada para el uso cotidiano.\n\n## Criterio\n\nEl proyecto priorizó una tecnología ya disponible para el equipo, evitando imponer una plataforma más compleja de mantener.",
        category: "Cliente",
        type: "Sistema de ventas",
        role: "Análisis y desarrollo",
        year: "2023",
        stack: ["Excel", "Modelado de datos", "Automatización"],
        outcomes: ["Ventas e inventario en un mismo flujo", "Reportes automatizados", "Operación basada en una herramienta familiar"],
        featured: true,
        order: 4,
        cover: { src: "/assets/images/portfolio/details-thumb_cana.webp", alt: "Interfaz del sistema de ventas de Caña Wasky", width: 1275, height: 850 },
        seo: { description: "Sistema de ventas, inventario y reportes creado para Caña Wasky." },
      },
      {
        id: "project-pachas-web",
        slug: "pachas-cafe-web",
        title: "Pacha’s Café",
        excerpt: "Presencia web para presentar menú, propuesta y ubicación del café.",
        body: "Proyecto web para organizar la información esencial de Pacha’s Café en una experiencia clara y adaptable a dispositivos móviles.",
        category: "Archivo de clientes",
        type: "Sitio web",
        role: "Diseño y desarrollo",
        year: "2024",
        stack: ["Web", "Diseño responsive"],
        outcomes: ["Menú y ubicación reunidos", "Experiencia adaptable"],
        featured: false,
        order: 5,
        seo: {},
      },
      {
        id: "project-municipalidad-rioja",
        slug: "municipalidad-de-rioja",
        title: "Municipalidad de Rioja",
        excerpt: "Propuesta para modernizar la presencia digital y facilitar información ciudadana.",
        body: "Concepto web orientado a ordenar información municipal y simplificar su consulta desde distintos dispositivos.",
        category: "Archivo de propuestas",
        type: "Propuesta web",
        role: "Diseño de interfaz",
        year: "2022",
        stack: ["Diseño web", "Arquitectura de información"],
        outcomes: ["Información organizada por necesidades", "Propuesta adaptable"],
        featured: false,
        order: 6,
        seo: {},
      },
      {
        id: "project-discord",
        slug: "discord",
        title: "Comunidades en Discord",
        excerpt: "Configuración y moderación de espacios digitales con roles y canales comprensibles.",
        body: "Experiencia organizando comunidades, permisos, canales y automatizaciones para mantener espacios digitales claros y seguros.",
        category: "Archivo",
        type: "Comunidades",
        role: "Configuración y moderación",
        year: "2018–2025",
        stack: ["Discord", "Bots", "Moderación"],
        outcomes: ["Roles y permisos claros", "Canales organizados", "Automatización de tareas repetitivas"],
        featured: false,
        order: 7,
        seo: {},
      },
    ],
    articles: [
      {
        id: "article-rice-visual-analysis",
        slug: "tesis-arroz-29-04-2025",
        title: "Análisis visual de factores que afectan el rendimiento del arroz",
        excerpt: "Segundo avance de investigación: observaciones de campo y entrevista con un especialista agrónomo.",
        body: "En esta segunda fase incorporé la experiencia del ingeniero agrónomo Ever Ramírez Rojas para complementar el análisis técnico con observaciones de campo.\n\n## Preguntas de investigación\n\nLa entrevista explora qué señales visuales permiten anticipar un buen rendimiento, qué factores son determinantes y en qué etapa del cultivo resulta más viable realizar la evaluación.\n\nEl objetivo de este avance es contrastar las variables del modelo con conocimiento práctico antes de ajustar la propuesta predictiva.",
        category: "Investigación",
        tags: ["Arroz", "Agronomía", "Datos"],
        publishedAt: "2025-04-29",
        readingMinutes: 6,
        cover: { src: "/assets/images/blog/blog-details1-tesis-29-04-2025.webp", alt: "Análisis visual de un cultivo de arroz", width: 1920, height: 850 },
        seo: {},
      },
      {
        id: "article-rice-tcn",
        slug: "tesis-arroz-22-04-2025",
        title: "Modelo predictivo de rendimiento de arroz con datos satelitales y climáticos",
        excerpt: "Un estudio sobre redes convolucionales temporales y datos multiespectrales aplicados a agricultura.",
        body: "La predicción temprana del rendimiento agrícola es una herramienta importante para la planificación. Este estudio revisa un método que combina redes convolucionales temporales con datos multiespectrales.\n\n## Datos utilizados\n\nEl trabajo considera índices de vegetación MODIS, variables climáticas y datos históricos de rendimiento entre 2012 y 2019.\n\n## Aspectos del modelo\n\n- Analiza múltiples variables de manera conjunta.\n- Identifica relaciones temporales.\n- Compara el error de predicción mediante MAE, RMSE y R².\n\nEl avance sirve como base técnica para adaptar el enfoque a información agrícola regional.",
        category: "Investigación",
        tags: ["Machine learning", "Satélites", "Agricultura"],
        publishedAt: "2025-04-22",
        readingMinutes: 8,
        cover: { src: "/assets/images/blog/blog-details1-tesis-22-04-2025.webp", alt: "Datos satelitales aplicados al cultivo de arroz", width: 1920, height: 850 },
        seo: {},
      },
      {
        id: "article-discord-business",
        slug: "discord-para-negocios",
        title: "Cómo usar Discord para tu negocio o comunidad online",
        excerpt: "Canales, roles, bots y criterios básicos para construir una comunidad organizada.",
        body: "Discord también puede servir como espacio de soporte, coordinación y comunidad para un negocio. La diferencia está en diseñar una estructura que las personas entiendan.\n\n## Un punto de partida\n\n- Define canales por propósito, no por ocurrencia.\n- Separa permisos de moderación y participación.\n- Automatiza tareas repetitivas con bots bien delimitados.\n- Documenta las reglas donde la comunidad pueda encontrarlas.\n\nUna comunidad sana necesita más que herramientas: requiere expectativas claras, moderación consistente y canales para escuchar a sus miembros.",
        category: "Comunidades",
        tags: ["Discord", "Moderación", "Comunidad"],
        publishedAt: "2025-04-21",
        readingMinutes: 4,
        cover: { src: "/assets/images/blog/blog-details1-discord.webp", alt: "Interfaz de una comunidad organizada en Discord", width: 1920, height: 850 },
        seo: {},
      },
    ],
  },
};
