import type { PortfolioEnvelope } from "@/types/content";

export const FALLBACK_ENVELOPE: PortfolioEnvelope = {
  schemaVersion: "1",
  siteKey: "velaarturo",
  publishedRevision: 3,
  generatedAt: "2026-09-05T12:11:43.000-05:00",
  data: {
    site: {
      name: "Arturo Vela",
      headline: "Diseño y construyo productos digitales que hacen simple lo complejo.",
      intro: "Ingeniero de sistemas y desarrollador web en Perú. Diseño interfaces, datos y servicios edge como un solo producto.",
      availability: "Abierto a conversar sobre productos, sistemas internos y colaboración técnica.",
      location: "Perú",
      bio: "Trabajo entre producto, interfaz e ingeniería. Me interesa entender primero el proceso real, reducir fricción y entregar sistemas que las personas puedan usar y mantener con confianza.",
      email: "velaarturo70@gmail.com",
      phone: "+51 963 653 154",
      cvUrl: "https://1drv.ms/b/s!AhTBs2k3EIAxjthfmoaQGB-VJxbvKA?e=jyDFsy",
      socials: [
        { label: "GitHub", url: "https://github.com/ArturoVela" },
        { label: "LinkedIn", url: "https://www.linkedin.com/in/arturo-vela-aa81242ba/" },
        { label: "Discord", url: "https://discord.gg/mnMkUXC5vK" },
      ],
      seo: {
        title: "Arturo Vela — Ingeniería de productos digitales",
        description: "Portafolio de Arturo Vela: aplicaciones web, sistemas internos, automatización e interfaces construidas desde Perú.",
        ogImage: "/og-card.png",
      },
    },
    services: [
      {
        id: "web-products",
        title: "Productos web",
        description: "Aplicaciones rápidas y accesibles, desde el flujo principal hasta el despliegue.",
        capabilities: ["React y TypeScript", "Diseño responsive", "Cloudflare Workers"],
      },
      {
        id: "internal-systems",
        title: "Sistemas internos",
        description: "Herramientas que ordenan información y reemplazan procesos manuales repetitivos.",
        capabilities: ["Modelado de datos", "Automatización", "Integraciones"],
      },
      {
        id: "ui-systems",
        title: "Sistemas de interfaz",
        description: "Lenguajes visuales consistentes que conectan productos de una misma familia.",
        capabilities: ["Chakra UI", "Tokens semánticos", "Accesibilidad"],
      },
    ],
    projects: [
      {
        id: "project-hub",
        slug: "hub",
        title: "Hub",
        excerpt: "39 herramientas cotidianas reunidas en una SPA local-first, rápida y modular.",
        body: "## El reto\n\nReunir utilidades de cálculo, texto, diseño, productividad y desarrollo sin convertir la portada en un paquete pesado.\n\n## La solución\n\nUna arquitectura React + Vite con carga diferida por herramienta. Los procesos sensibles permanecen en el navegador siempre que es posible; el Worker atiende solo las funciones que necesitan API o persistencia.\n\n## Enfoque\n\nEl catálogo funciona como fuente de verdad para rutas, búsqueda y relaciones. Favoritos, actividad reciente y preferencias viven localmente, mientras D1 guarda únicamente enlaces cortos y rankings.",
        category: "Producto personal",
        type: "Aplicación web",
        role: "Diseño y desarrollo integral",
        year: "2026",
        stack: ["React", "TypeScript", "Vite", "Chakra UI", "Cloudflare Workers", "D1"],
        outcomes: ["39 herramientas agrupadas en 11 categorías", "Procesamiento local para archivos y datos sensibles", "Carga bajo demanda por cada herramienta"],
        liveUrl: "https://hub.velaarturo.com",
        featured: true,
        order: 1,
        seo: { description: "Hub reúne 39 herramientas web en una SPA local-first construida con React, Vite y Cloudflare Workers." },
      },
      {
        id: "project-un-ramito",
        slug: "un-ramito",
        title: "Un ramito",
        excerpt: "Una experiencia para crear y compartir ramos virtuales con dedicatorias privadas.",
        body: "## Una experiencia pequeña con privacidad real\n\nLa persona diseña un ramo, escribe una dedicatoria y comparte un enlace. La dedicatoria se cifra en el navegador antes de salir del dispositivo.\n\n## Arquitectura\n\nCloudflare D1 conserva solo el sobre cifrado durante 90 días. La clave viaja en el fragmento de la URL, que no se envía al servidor.",
        category: "Experiencia digital",
        type: "Aplicación web",
        role: "Producto, diseño y desarrollo",
        year: "2026",
        stack: ["React", "TypeScript", "Vite", "Chakra UI", "Web Crypto", "Cloudflare D1"],
        outcomes: ["Cifrado en el navegador", "Enlaces privados fáciles de compartir", "Caducidad automática de 90 días"],
        liveUrl: "https://un-ramito.withered-hat-79c9.workers.dev",
        featured: true,
        order: 2,
        seo: { description: "Un ramito permite diseñar y compartir ramos virtuales con dedicatorias cifradas en el navegador." },
      },
      {
        id: "project-security-lab",
        slug: "security-lab",
        title: "Security Lab",
        excerpt: "Laboratorio privado para comparar cuatro generaciones de auditoría y sus entornos de prueba.",
        body: "## Aprender comparando\n\nEl laboratorio organiza cuatro versiones de una auditoría junto a sus ambientes de prueba. La matriz hace visibles los cambios entre una implementación original, una versión reforzada y reemplazos posteriores.\n\n## Límites claros\n\nLos módulos están diseñados para sistemas propios, académicos o con autorización expresa. El acceso es privado y las utilidades generales se separaron en Hub.",
        category: "Seguridad aplicada",
        type: "Laboratorio web privado",
        role: "Arquitectura y desarrollo",
        year: "2026",
        stack: ["Next.js", "React", "TypeScript", "Chakra UI", "Supabase"],
        outcomes: ["Comparación de cuatro generaciones", "Ocho módulos organizados en una matriz", "Separación de utilidades generales hacia Hub"],
        featured: true,
        order: 3,
        seo: { description: "Laboratorio privado de Arturo Vela para comparar generaciones de auditoría y entornos de prueba." },
      },
      {
        id: "project-cana-wasky",
        slug: "cana-wasky",
        title: "Caña Wasky",
        excerpt: "Sistema en Excel para organizar ventas, inventario y reportes de un negocio gastronómico.",
        body: "## Contexto\n\nCaña Wasky necesitaba reunir el control comercial en una herramienta comprensible para la operación diaria.\n\n## Solución\n\nSe estructuró un sistema de ventas e inventario en Excel, con reportes automatizados y una interfaz pensada para el uso cotidiano.\n\n## Criterio\n\nEl proyecto priorizó una tecnología ya disponible para el equipo, evitando imponer una plataforma más compleja de mantener.",
        category: "Cliente",
        type: "Sistema de ventas",
        role: "Análisis y desarrollo",
        year: "2023",
        stack: ["Excel", "Modelado de datos", "Automatización"],
        outcomes: ["Ventas e inventario en un mismo flujo", "Reportes automatizados", "Operación basada en una herramienta familiar"],
        featured: true,
        order: 4,
        cover: { src: "/assets/images/portfolio/details-thumb_cana.webp", alt: "Interfaz del sistema de ventas de Caña Wasky", width: 1275, height: 850 },
        seo: { description: "Sistema de ventas, inventario y reportes creado para Caña Wasky." },
      },
      {
        id: "project-porta",
        slug: "porta",
        title: "Porta",
        excerpt: "Portafolio profesional con contenido desacoplado, SEO en el edge y comentarios protegidos.",
        body: "## El portafolio como producto\n\nPorta reúne proyectos, artículos y perfil en una SPA rápida, pero conserva metadatos y respuestas HTML útiles para buscadores desde el Worker.\n\n## Arquitectura\n\nEl mismo Cloudflare Worker sirve la aplicación, la API de contenido, el sitemap y el feed. Un enlace privado con Second Brain entrega publicaciones y medios; si ese origen no responde, una cadena de caché y respaldo mantiene el sitio disponible.\n\n## Operación\n\nLos comentarios se guardan en una D1 independiente y Turnstile protege la publicación. El código del portafolio permanece público para que la arquitectura sea verificable.",
        category: "Producto personal",
        type: "Portafolio web",
        role: "Diseño, arquitectura y desarrollo",
        year: "2025–2026",
        stack: ["React", "TypeScript", "Vite", "Chakra UI", "Cloudflare Workers", "D1"],
        outcomes: ["Contenido desacoplado con respaldo local", "SEO, sitemap y feed generados en el edge", "Repositorio público y despliegue verificable"],
        liveUrl: "https://velaarturo.com",
        repoUrl: "https://github.com/ArturoVela/Porta",
        featured: false,
        order: 5,
        seo: { description: "Porta es el portafolio de Arturo Vela, construido con React, Vite, Chakra UI y Cloudflare Workers." },
      },
      {
        id: "project-second-brain",
        slug: "second-brain",
        title: "Second Brain",
        excerpt: "Espacio personal para capturar, relacionar y revisar información, tareas, archivos y proyectos.",
        body: "## Un sistema personal, no una colección de pantallas\n\nSecond Brain integra captura, objetos universales, edición enriquecida, búsqueda, relaciones, calendario y revisión en un mismo espacio privado.\n\n## Arquitectura Cloudflare-first\n\nD1 conserva los datos relacionales y la búsqueda; R2 guarda archivos versionados; Queues ejecuta indexación y extracción; y Cloudflare Access protege los entornos remotos.\n\n## Integración\n\nTambién funciona como fuente editorial privada de este portafolio mediante un contrato versionado y un Service Binding entre Workers.",
        category: "Producto personal",
        type: "Sistema web privado",
        role: "Producto, arquitectura y desarrollo",
        year: "2026",
        stack: ["React", "TypeScript", "Mantine", "Cloudflare Workers", "D1", "R2", "Queues"],
        outcomes: ["Captura, búsqueda y revisión en un solo sistema", "Archivos privados con versiones", "Publicación desacoplada hacia Porta"],
        featured: false,
        order: 6,
        seo: { description: "Second Brain es un sistema personal privado para conocimiento, planificación, archivos y publicación de contenido." },
      },
      {
        id: "project-db-nieto",
        slug: "db-nieto",
        title: "DB Nieto",
        excerpt: "Inteligencia comercial que preserva seis ejercicios históricos y los convierte en paneles consultables.",
        body: "## Del archivo operativo a una fuente consultable\n\nDB Nieto conserva información comercial de seis ejercicios procedentes de Visual FoxPro y la presenta en una aplicación BI protegida.\n\n## Migración auditable\n\nLos archivos DBF originales permanecen como fuente de trazabilidad. Un generador idempotente prepara las cargas hacia D1, mientras React y Chakra UI presentan los indicadores por periodo.\n\n## Acceso\n\nLa aplicación está en línea, pero Cloudflare Access limita su uso a identidades autorizadas porque trabaja con información interna.",
        category: "Sistema interno",
        type: "Dashboard privado",
        role: "Migración, arquitectura y desarrollo",
        year: "2026",
        stack: ["React", "TypeScript", "Vite", "Cloudflare Workers", "D1", "Cloudflare Access"],
        outcomes: ["Seis ejercicios comerciales reunidos", "Migración idempotente desde DBF", "Acceso protegido sin exponer las fuentes originales"],
        liveUrl: "https://db.nieto.velaarturo.com",
        featured: false,
        order: 7,
        seo: { description: "DB Nieto transforma seis ejercicios históricos de Visual FoxPro en una aplicación BI privada sobre Cloudflare." },
      },
      {
        id: "project-nieto-import",
        slug: "nieto-import",
        title: "Nieto Import",
        excerpt: "Sistema interno que centraliza etiquetas, procesos, documentación y herramientas administrativas.",
        body: "## Operación reunida\n\nNieto Import concentra utilidades que antes estaban dispersas: generación e impresión de etiquetas, documentación por áreas, firmas corporativas y formularios de gestión.\n\n## Alcance\n\nEl sistema atiende procesos de Nieto Import y Agromaf desde una interfaz responsive con permisos, búsqueda y flujos adaptados al trabajo cotidiano.\n\n## Acceso\n\nLa aplicación está desplegada, pero requiere una cuenta autorizada. El repositorio y los datos de operación permanecen privados.",
        category: "Sistema interno",
        type: "Aplicación web privada",
        role: "Desarrollo full-stack y evolución del producto",
        year: "2026",
        stack: ["Next.js", "React", "TypeScript", "Supabase", "Firebase", "Capacitor"],
        outcomes: ["Herramientas administrativas centralizadas", "Soporte para dos empresas", "Experiencia web y envoltorio móvil"],
        liveUrl: "https://portal.nietoimport.com",
        featured: false,
        order: 8,
        seo: { description: "Nieto Import es una aplicación privada para etiquetas, documentación y procesos administrativos." },
      },
      {
        id: "project-mercadillo",
        slug: "mercadillo-pe",
        title: "Mercadillo.pe",
        excerpt: "Plataforma de delivery y gestión de restaurantes con catálogo, pedidos y operación administrativa.",
        body: "## Producto colaborativo\n\nMercadillo.pe conecta clientes, restaurantes y reparto dentro de una experiencia responsive. El trabajo abarca descubrimiento, menús, carrito, checkout y seguimiento de pedidos.\n\n## Operación\n\nAdemás del recorrido público, el sistema incorpora gestión de comercios, inventario, promociones, comunicaciones y herramientas administrativas sobre Supabase.\n\n## Estado\n\nEl proyecto y su despliegue actual son privados; esta ficha documenta el alcance sin exponer código ni datos.",
        category: "Proyecto colaborativo",
        type: "Plataforma web privada",
        role: "Desarrollo full-stack en equipo",
        year: "2026",
        stack: ["Next.js", "React", "TypeScript", "Supabase", "Tailwind CSS"],
        outcomes: ["Flujo completo de catálogo y pedidos", "Módulos para comercios y administración", "Diseño responsive orientado al mercado local"],
        featured: false,
        order: 9,
        seo: { description: "Mercadillo.pe es una plataforma privada de delivery y gestión para restaurantes." },
      },
      {
        id: "project-kc-automotriz",
        slug: "kc-automotriz",
        title: "KC Automotriz",
        excerpt: "Catálogo de vehículos con filtros, cotizador de cuotas y un panel para administrar inventario y contactos.",
        body: "## Una vitrina que también opera\n\nKC Automotriz combina un catálogo visual para compradores con herramientas de gestión para el equipo. Los vehículos pueden filtrarse por marca, modelo, kilometraje y condición.\n\n## Conversión y administración\n\nEl cotizador ayuda a proyectar cuotas, mientras los puntos de contacto registran interesados. Un panel privado organiza inventario, marcas, promociones y seguimiento.\n\n## Estado\n\nEl repositorio y la demostración permanecen privados porque el proyecto corresponde a un cliente.",
        category: "Cliente",
        type: "Sitio y panel privados",
        role: "Diseño y desarrollo full-stack",
        year: "2026",
        stack: ["Next.js", "React", "Supabase", "PostgreSQL", "CSS"],
        outcomes: ["Catálogo con filtrado avanzado", "Cotizador interactivo de financiamiento", "Panel para inventario y prospectos"],
        featured: false,
        order: 10,
        seo: { description: "KC Automotriz combina catálogo, cotizador y gestión privada de inventario de vehículos." },
      },
      {
        id: "project-pachas-web",
        slug: "pachas-cafe-web",
        title: "Pacha’s Café",
        excerpt: "Sistema local de ventas con productos, clientes, compras, caja e inventario para la operación del café.",
        body: "## Operación completa\n\nEl proyecto reúne ventas, productos, variantes, clientes, proveedores, compras, caja y fidelización en un flujo pensado para la operación diaria de Pacha’s Café.\n\n## Arquitectura local\n\nUna interfaz PHP consume una API Spring Boot con persistencia H2. El entorno incluye datos de demostración y perfiles de administración para comprobar el recorrido completo sin depender de servicios externos.\n\n## Estado\n\nEl sistema se ejecuta de forma local y el repositorio permanece privado por contener lógica de negocio del cliente.",
        category: "Cliente",
        type: "Sistema local privado",
        role: "Desarrollo full-stack",
        year: "2026",
        stack: ["PHP", "Spring Boot", "Java", "H2", "Docker"],
        outcomes: ["Ventas e inventario conectados", "Compras, caja y fidelización integradas", "Entorno local reproducible con datos de demostración"],
        featured: false,
        order: 11,
        seo: { description: "Sistema privado de ventas, inventario, compras y caja desarrollado para Pacha’s Café." },
      },
      {
        id: "project-misterio-maria",
        slug: "misterio-maria",
        title: "El misterio de María del Carmen",
        excerpt: "Experiencia personalizada para descubrir un regalo mediante pistas, una teoría y una clave secreta.",
        body: "## Un regalo convertido en recorrido\n\nLa experiencia presenta cuatro pistas y permite construir una teoría antes de intentar revelar el regalo. El progreso se conserva para continuar más tarde.\n\n## Privacidad desde la arquitectura\n\nLa respuesta y la fotografía no forman parte de la carga inicial. El Worker solo las entrega cuando valida la clave en el servidor, y D1 conserva borradores e intentos sin exponer el contenido protegido.\n\n## Acceso\n\nLa experiencia está desplegada, pero su contenido final requiere la clave de la persona destinataria.",
        category: "Regalo digital",
        type: "Experiencia web privada",
        role: "Concepto, diseño y desarrollo",
        year: "2026",
        stack: ["Next.js", "React", "TypeScript", "Vinext", "Cloudflare Workers", "D1"],
        outcomes: ["Recorrido interactivo de cuatro pistas", "Respuesta y fotografía protegidas en el servidor", "Borradores recuperables entre sesiones"],
        liveUrl: "https://regalomaria04.withered-hat-79c9.workers.dev",
        featured: false,
        order: 12,
        seo: { description: "Experiencia web privada para descubrir un regalo mediante pistas y una clave secreta." },
      },
      {
        id: "project-cumpleanos",
        slug: "cumpleanos",
        title: "Cumpleaños",
        excerpt: "Experiencias privadas de cumpleaños con contenido personalizado, acceso por contraseña y medios protegidos.",
        body: "## Un formato reutilizable y personal\n\nCada persona recibe una ruta y una edición visual propia. El contenido se organiza en un registro privado para incorporar nuevos cumpleaños sin duplicar la aplicación.\n\n## Protección\n\nLas credenciales y sesiones viven en D1; las imágenes privadas permanecen en R2. La portada pública responde como una página no encontrada y solo las rutas destinadas exponen el inicio de sesión.\n\n## Estado\n\nEl proyecto está desplegado, pero no ofrece una demostración pública porque todo el contenido está dirigido a personas concretas.",
        category: "Experiencia digital",
        type: "Aplicación web privada",
        role: "Diseño, desarrollo y operación",
        year: "2026",
        stack: ["React", "TypeScript", "Vite", "Chakra UI", "Cloudflare Workers", "D1", "R2"],
        outcomes: ["Ediciones visuales por persona y año", "Sesiones protegidas con credenciales", "Medios privados fuera del bundle público"],
        featured: false,
        order: 13,
        seo: { description: "Sistema privado para crear experiencias de cumpleaños personalizadas y proteger sus medios." },
      },
      {
        id: "project-seas-venta",
        slug: "seas-venta",
        title: "SEAS Venta",
        excerpt: "Aplicación móvil colaborativa para ventas, caja, inventario, clientes y operación de tiendas de ropa.",
        body: "## Gestión desde el teléfono\n\nSEAS Venta lleva el punto de venta y la operación diaria de una tienda a una aplicación Flutter: catálogo, variantes, clientes, compras, caja, devoluciones, promociones y reportes.\n\n## Trabajo sin conexión\n\nEl catálogo y los clientes pueden mantenerse en caché; las ventas creadas sin red entran en una cola local y se sincronizan al recuperar conectividad.\n\n## Estado\n\nEs un desarrollo colaborativo en curso. El repositorio y los servicios de datos permanecen privados.",
        category: "Proyecto colaborativo",
        type: "Aplicación móvil privada",
        role: "Desarrollo de producto en equipo",
        year: "2026",
        stack: ["Flutter", "Dart", "GetX", "Supabase", "Hive", "Firebase"],
        outcomes: ["Punto de venta y caja móvil", "Inventario, clientes y reportes integrados", "Cola offline para ventas pendientes"],
        featured: false,
        order: 14,
        seo: { description: "SEAS Venta es una aplicación Flutter privada para gestionar ventas y operación de tiendas de ropa." },
      },
      {
        id: "project-municipalidad-rioja",
        slug: "municipalidad-de-rioja",
        title: "Municipalidad de Rioja",
        excerpt: "Propuesta para modernizar la presencia digital y facilitar información ciudadana.",
        body: "Concepto web orientado a ordenar información municipal y simplificar su consulta desde distintos dispositivos.",
        category: "Archivo de propuestas",
        type: "Propuesta web",
        role: "Diseño de interfaz",
        year: "2022",
        stack: ["Diseño web", "Arquitectura de información"],
        outcomes: ["Información organizada por necesidades", "Propuesta adaptable"],
        featured: false,
        order: 15,
        seo: {},
      },
      {
        id: "project-discord",
        slug: "discord",
        title: "Comunidades en Discord",
        excerpt: "Configuración y moderación de espacios digitales con roles y canales comprensibles.",
        body: "Experiencia organizando comunidades, permisos, canales y automatizaciones para mantener espacios digitales claros y seguros.",
        category: "Archivo",
        type: "Comunidades",
        role: "Configuración y moderación",
        year: "2018–2025",
        stack: ["Discord", "Bots", "Moderación"],
        outcomes: ["Roles y permisos claros", "Canales organizados", "Automatización de tareas repetitivas"],
        featured: false,
        order: 16,
        seo: {},
      },
      {
        id: "project-nieto-hub",
        slug: "nieto-hub",
        title: "NIETO Hub",
        excerpt: "Portafolio público de los productos digitales desarrollados para NIETO.",
        body: "## Un punto de entrada común\n\nNIETO Hub reúne en una sola página los productos digitales desarrollados para la empresa, con acceso directo a cada plataforma y fichas públicas de proyecto.\n\n## Contenido seguro y actualizable\n\nLas fichas describen objetivos, tecnologías y resultados sin exponer repositorios, credenciales ni datos internos. El contenido publicado se administra desde Second Brain y puede incorporar nuevos proyectos sin reconstruir el sitio.",
        category: "Cliente",
        type: "Portafolio web",
        role: "Diseño, arquitectura y desarrollo",
        year: "2026",
        stack: ["React", "TypeScript", "Vite", "Chakra UI", "Cloudflare Workers"],
        outcomes: ["Productos de NIETO reunidos en una sola vista", "Detalles públicos sin exponer información interna", "Contenido desacoplado y preparado para crecer"],
        liveUrl: "https://nieto.velaarturo.com",
        featured: false,
        order: 17,
        seo: { description: "NIETO Hub reúne los productos digitales desarrollados para NIETO en un portafolio público y seguro." },
      },
    ],
    articles: [
      {
        id: "article-rice-visual-analysis",
        slug: "tesis-arroz-29-04-2025",
        title: "Análisis visual de factores que afectan el rendimiento del arroz",
        excerpt: "Segundo avance de investigación: observaciones de campo y entrevista con un especialista agrónomo.",
        body: "En esta segunda fase incorporé la experiencia del ingeniero agrónomo Ever Ramírez Rojas para complementar el análisis técnico con observaciones de campo.\n\n## Preguntas de investigación\n\nLa entrevista explora qué señales visuales permiten anticipar un buen rendimiento, qué factores son determinantes y en qué etapa del cultivo resulta más viable realizar la evaluación.\n\nEl objetivo de este avance es contrastar las variables del modelo con conocimiento práctico antes de ajustar la propuesta predictiva.",
        category: "Investigación",
        tags: ["Arroz", "Agronomía", "Datos"],
        publishedAt: "2025-04-29",
        readingMinutes: 6,
        cover: { src: "/assets/images/blog/blog-details1-tesis-29-04-2025.webp", alt: "Análisis visual de un cultivo de arroz", width: 1920, height: 850 },
        seo: {},
      },
      {
        id: "article-rice-tcn",
        slug: "tesis-arroz-22-04-2025",
        title: "Modelo predictivo de rendimiento de arroz con datos satelitales y climáticos",
        excerpt: "Un estudio sobre redes convolucionales temporales y datos multiespectrales aplicados a agricultura.",
        body: "La predicción temprana del rendimiento agrícola es una herramienta importante para la planificación. Este estudio revisa un método que combina redes convolucionales temporales con datos multiespectrales.\n\n## Datos utilizados\n\nEl trabajo considera índices de vegetación MODIS, variables climáticas y datos históricos de rendimiento entre 2012 y 2019.\n\n## Aspectos del modelo\n\n- Analiza múltiples variables de manera conjunta.\n- Identifica relaciones temporales.\n- Compara el error de predicción mediante MAE, RMSE y R².\n\nEl avance sirve como base técnica para adaptar el enfoque a información agrícola regional.",
        category: "Investigación",
        tags: ["Machine learning", "Satélites", "Agricultura"],
        publishedAt: "2025-04-22",
        readingMinutes: 8,
        cover: { src: "/assets/images/blog/blog-details1-tesis-22-04-2025.webp", alt: "Datos satelitales aplicados al cultivo de arroz", width: 1920, height: 850 },
        seo: {},
      },
      {
        id: "article-discord-business",
        slug: "discord-para-negocios",
        title: "Cómo usar Discord para tu negocio o comunidad online",
        excerpt: "Canales, roles, bots y criterios básicos para construir una comunidad organizada.",
        body: "Discord también puede servir como espacio de soporte, coordinación y comunidad para un negocio. La diferencia está en diseñar una estructura que las personas entiendan.\n\n## Un punto de partida\n\n- Define canales por propósito, no por ocurrencia.\n- Separa permisos de moderación y participación.\n- Automatiza tareas repetitivas con bots bien delimitados.\n- Documenta las reglas donde la comunidad pueda encontrarlas.\n\nUna comunidad sana necesita más que herramientas: requiere expectativas claras, moderación consistente y canales para escuchar a sus miembros.",
        category: "Comunidades",
        tags: ["Discord", "Moderación", "Comunidad"],
        publishedAt: "2025-04-21",
        readingMinutes: 4,
        cover: { src: "/assets/images/blog/blog-details1-discord.webp", alt: "Interfaz de una comunidad organizada en Discord", width: 1920, height: 850 },
        seo: {},
      },
    ],
  },
};
