import type { PortfolioEnvelope } from "@/types/content";

export const FALLBACK_ENVELOPE: PortfolioEnvelope = {
  schemaVersion: "1",
  siteKey: "velaarturo",
  publishedRevision: 5,
  generatedAt: "2026-09-12T08:24:04.000-05:00",
  data: {
    site: {
      name: "Arturo Vela",
      headline: "Diseño y construyo productos digitales que hacen simple lo complejo.",
      intro: "Ingeniero de sistemas y desarrollador web en Perú. Diseño interfaces, datos y servicios edge como un solo producto.",
      availability: "Abierto a conversar sobre productos, sistemas internos y colaboración técnica.",
      location: "Perú",
      bio: "Trabajo entre producto, interfaz e ingeniería. Me interesa entender primero el proceso real, reducir fricción y entregar sistemas que las personas puedan usar y mantener con confianza.",
      email: "velaarturo70@gmail.com",
      phone: "+51 963 653 154",
      cvUrl: "https://1drv.ms/b/s!AhTBs2k3EIAxjthfmoaQGB-VJxbvKA?e=jyDFsy",
      socials: [
        { label: "GitHub", url: "https://github.com/ArturoVela" },
        { label: "LinkedIn", url: "https://www.linkedin.com/in/arturo-vela-aa81242ba/" },
        { label: "Discord", url: "https://discord.gg/mnMkUXC5vK" },
      ],
      seo: {
        title: "Arturo Vela — Ingeniería de productos digitales",
        description: "Portafolio de Arturo Vela: aplicaciones web, sistemas internos, automatización e interfaces construidas desde Perú.",
        ogImage: "/og-card.png",
      },
    },
    services: [
      {
        id: "web-products",
        title: "Productos web",
        description: "Aplicaciones rápidas y accesibles, desde el flujo principal hasta el despliegue.",
        capabilities: ["React y TypeScript", "Diseño responsive", "Cloudflare Workers"],
      },
      {
        id: "internal-systems",
        title: "Sistemas internos",
        description: "Herramientas que ordenan información y reemplazan procesos manuales repetitivos.",
        capabilities: ["Modelado de datos", "Automatización", "Integraciones"],
      },
      {
        id: "ui-systems",
        title: "Sistemas de interfaz",
        description: "Lenguajes visuales consistentes que conectan productos de una misma familia.",
        capabilities: ["Chakra UI", "Tokens semánticos", "Accesibilidad"],
      },
    ],
    projects: [
      {
        id: "project-hub",
        slug: "hub",
        title: "Hub",
        excerpt: "39 herramientas cotidianas reunidas en una SPA local-first, rápida y modular.",
        body: "## El reto\n\nReunir utilidades de cálculo, texto, diseño, productividad y desarrollo sin convertir la portada en un paquete pesado.\n\n## La solución\n\nUna arquitectura React + Vite con carga diferida por herramienta. Los procesos sensibles permanecen en el navegador siempre que es posible; el Worker atiende solo las funciones que necesitan API o persistencia.\n\n## Enfoque\n\nEl catálogo funciona como fuente de verdad para rutas, búsqueda y relaciones. Favoritos, actividad reciente y preferencias viven localmente, mientras D1 guarda únicamente enlaces cortos y rankings.",
        category: "Producto personal",
        type: "Aplicación web",
        role: "Diseño y desarrollo integral",
        year: "2026",
        stack: ["React", "TypeScript", "Vite", "Chakra UI", "Cloudflare Workers", "D1"],
        outcomes: ["39 herramientas agrupadas en 11 categorías", "Procesamiento local para archivos y datos sensibles", "Carga bajo demanda por cada herramienta"],
        liveUrl: "https://hub.velaarturo.com",
        featured: true,
        order: 1,
        seo: { description: "Hub reúne 39 herramientas web en una SPA local-first construida con React, Vite y Cloudflare Workers." },
      },
      {
        id: "project-un-ramito",
        slug: "un-ramito",
        title: "Un ramito",
        excerpt: "Una experiencia para crear y compartir ramos virtuales con dedicatorias privadas.",
        body: "## Una experiencia pequeña con privacidad real\n\nLa persona diseña un ramo, escribe una dedicatoria y comparte un enlace. La dedicatoria se cifra en el navegador antes de salir del dispositivo.\n\n## Arquitectura\n\nCloudflare D1 conserva solo el sobre cifrado durante 90 días. La clave viaja en el fragmento de la URL, que no se envía al servidor.",
        category: "Experiencia digital",
        type: "Aplicación web",
        role: "Producto, diseño y desarrollo",
        year: "2026",
        stack: ["React", "TypeScript", "Vite", "Chakra UI", "Web Crypto", "Cloudflare D1"],
        outcomes: ["Cifrado en el navegador", "Enlaces privados fáciles de compartir", "Caducidad automática de 90 días"],
        liveUrl: "https://un-ramito.withered-hat-79c9.workers.dev",
        featured: true,
        order: 2,
        seo: { description: "Un ramito permite diseñar y compartir ramos virtuales con dedicatorias cifradas en el navegador." },
      },
      {
        id: "project-security-lab",
        slug: "security-lab",
        title: "Security Lab",
        excerpt: "Laboratorio privado para comparar cuatro generaciones de auditoría y sus entornos de prueba.",
        body: "## Aprender comparando\n\nEl laboratorio organiza cuatro versiones de una auditoría junto a sus ambientes de prueba. La matriz hace visibles los cambios entre una implementación original, una versión reforzada y reemplazos posteriores.\n\n## Límites claros\n\nLos módulos están diseñados para sistemas propios, académicos o con autorización expresa. El acceso es privado y las utilidades generales se separaron en Hub.",
        category: "Seguridad aplicada",
        type: "Laboratorio web privado",
        role: "Arquitectura y desarrollo",
        year: "2026",
        stack: ["Next.js", "React", "TypeScript", "Chakra UI", "Supabase"],
        outcomes: ["Comparación de cuatro generaciones", "Ocho módulos organizados en una matriz", "Separación de utilidades generales hacia Hub"],
        featured: true,
        order: 3,
        seo: { description: "Laboratorio privado de Arturo Vela para comparar generaciones de auditoría y entornos de prueba." },
      },
      {
        id: "project-cana-wasky",
        slug: "cana-wasky",
        title: "Caña Wasky",
        excerpt: "Sistema en Excel para organizar ventas, inventario y reportes de un negocio gastronómico.",
        body: "## Contexto\n\nCaña Wasky necesitaba reunir el control comercial en una herramienta comprensible para la operación diaria.\n\n## Solución\n\nSe estructuró un sistema de ventas e inventario en Excel, con reportes automatizados y una interfaz pensada para el uso cotidiano.\n\n## Criterio\n\nEl proyecto priorizó una tecnología ya disponible para el equipo, evitando imponer una plataforma más compleja de mantener.",
        category: "Cliente",
        type: "Sistema de ventas",
        role: "Análisis y desarrollo",
        year: "2023",
        stack: ["Excel", "Modelado de datos", "Automatización"],
        outcomes: ["Ventas e inventario en un mismo flujo", "Reportes automatizados", "Operación basada en una herramienta familiar"],
        featured: true,
        order: 4,
        cover: { src: "/assets/images/portfolio/details-thumb_cana.webp", alt: "Interfaz del sistema de ventas de Caña Wasky", width: 1275, height: 850 },
        seo: { description: "Sistema de ventas, inventario y reportes creado para Caña Wasky." },
      },
      {
        id: "project-porta",
        slug: "porta",
        title: "Porta",
        excerpt: "Portafolio profesional con contenido desacoplado, SEO en el edge y comentarios protegidos.",
        body: "## El portafolio como producto\n\nPorta reúne proyectos, artículos y perfil en una SPA rápida, pero conserva metadatos y respuestas HTML útiles para buscadores desde el Worker.\n\n## Arquitectura\n\nEl mismo Cloudflare Worker sirve la aplicación, la API de contenido, el sitemap y el feed. Un enlace privado con Second Brain entrega publicaciones y medios; si ese origen no responde, una cadena de caché y respaldo mantiene el sitio disponible.\n\n## Operación\n\nLos comentarios se guardan en una D1 independiente y Turnstile protege la publicación. El código del portafolio permanece público para que la arquitectura sea verificable.",
        category: "Producto personal",
        type: "Portafolio web",
        role: "Diseño, arquitectura y desarrollo",
        year: "2025–2026",
        stack: ["React", "TypeScript", "Vite", "Chakra UI", "Cloudflare Workers", "D1"],
        outcomes: ["Contenido desacoplado con respaldo local", "SEO, sitemap y feed generados en el edge", "Repositorio público y despliegue verificable"],
        liveUrl: "https://velaarturo.com",
        repoUrl: "https://github.com/ArturoVela/Porta",
        featured: false,
        order: 5,
        seo: { description: "Porta es el portafolio de Arturo Vela, construido con React, Vite, Chakra UI y Cloudflare Workers." },
      },
      {
        id: "project-second-brain",
        slug: "second-brain",
        title: "Second Brain",
        excerpt: "Espacio personal para capturar, relacionar y revisar información, tareas, archivos y proyectos.",
        body: "## Un sistema personal, no una colección de pantallas\n\nSecond Brain integra captura, objetos universales, edición enriquecida, búsqueda, relaciones, calendario y revisión en un mismo espacio privado.\n\n## Arquitectura Cloudflare-first\n\nD1 conserva los datos relacionales y la búsqueda; R2 guarda archivos versionados; Queues ejecuta indexación y extracción; y Cloudflare Access protege los entornos remotos.\n\n## Integración\n\nTambién funciona como fuente editorial privada de este portafolio mediante un contrato versionado y un Service Binding entre Workers.",
        category: "Producto personal",
        type: "Sistema web privado",
        role: "Producto, arquitectura y desarrollo",
        year: "2026",
        stack: ["React", "TypeScript", "Mantine", "Cloudflare Workers", "D1", "R2", "Queues"],
        outcomes: ["Captura, búsqueda y revisión en un solo sistema", "Archivos privados con versiones", "Publicación desacoplada hacia Porta"],
        featured: false,
        order: 6,
        seo: { description: "Second Brain es un sistema personal privado para conocimiento, planificación, archivos y publicación de contenido." },
      },
      {
        id: "project-db-nieto",
        slug: "db-nieto",
        title: "DB Nieto",
        excerpt: "Inteligencia comercial que preserva seis ejercicios históricos y los convierte en paneles consultables.",
        body: "## Del archivo operativo a una fuente consultable\n\nDB Nieto conserva información comercial de seis ejercicios procedentes de Visual FoxPro y la presenta en una aplicación BI protegida.\n\n## Migración auditable\n\nLos archivos DBF originales permanecen como fuente de trazabilidad. Un generador idempotente prepara las cargas hacia D1, mientras React y Chakra UI presentan los indicadores por periodo.\n\n## Acceso\n\nLa aplicación está en línea, pero Cloudflare Access limita su uso a identidades autorizadas porque trabaja con información interna.",
        category: "Sistema interno",
        type: "Dashboard privado",
        role: "Migración, arquitectura y desarrollo",
        year: "2026",
        stack: ["React", "TypeScript", "Vite", "Cloudflare Workers", "D1", "Cloudflare Access"],
        outcomes: ["Seis ejercicios comerciales reunidos", "Migración idempotente desde DBF", "Acceso protegido sin exponer las fuentes originales"],
        liveUrl: "https://db.nieto.velaarturo.com",
        featured: false,
        order: 7,
        seo: { description: "DB Nieto transforma seis ejercicios históricos de Visual FoxPro en una aplicación BI privada sobre Cloudflare." },
      },
      {
        id: "project-nieto-import",
        slug: "nieto-import",
        title: "Nieto Import",
        excerpt: "Sistema interno que centraliza etiquetas, procesos, documentación y herramientas administrativas.",
        body: "## Operación reunida\n\nNieto Import concentra utilidades que antes estaban dispersas: generación e impresión de etiquetas, documentación por áreas, firmas corporativas y formularios de gestión.\n\n## Alcance\n\nEl sistema atiende procesos de Nieto Import y Agromaf desde una interfaz responsive con permisos, búsqueda y flujos adaptados al trabajo cotidiano.\n\n## Acceso\n\nLa aplicación está desplegada, pero requiere una cuenta autorizada. El repositorio y los datos de operación permanecen privados.",
        category: "Sistema interno",
        type: "Aplicación web privada",
        role: "Desarrollo full-stack y evolución del producto",
        year: "2026",
        stack: ["Next.js", "React", "TypeScript", "Supabase", "Firebase", "Capacitor"],
        outcomes: ["Herramientas administrativas centralizadas", "Soporte para dos empresas", "Experiencia web y envoltorio móvil"],
        liveUrl: "https://portal.nietoimport.com",
        featured: false,
        order: 8,
        seo: { description: "Nieto Import es una aplicación privada para etiquetas, documentación y procesos administrativos." },
      },
      {
        id: "project-mercadillo",
        slug: "mercadillo-pe",
        title: "Mercadillo.pe",
        excerpt: "Plataforma de delivery y gestión de restaurantes con catálogo, pedidos y operación administrativa.",
        body: "## Producto colaborativo\n\nMercadillo.pe conecta clientes, restaurantes y reparto dentro de una experiencia responsive. El trabajo abarca descubrimiento, menús, carrito, checkout y seguimiento de pedidos.\n\n## Operación\n\nAdemás del recorrido público, el sistema incorpora gestión de comercios, inventario, promociones, comunicaciones y herramientas administrativas sobre Supabase.\n\n## Estado\n\nEl proyecto y su despliegue actual son privados; esta ficha documenta el alcance sin exponer código ni datos.",
        category: "Proyecto colaborativo",
        type: "Plataforma web privada",
        role: "Desarrollo full-stack en equipo",
        year: "2026",
        stack: ["Next.js", "React", "TypeScript", "Supabase", "Tailwind CSS"],
        outcomes: ["Flujo completo de catálogo y pedidos", "Módulos para comercios y administración", "Diseño responsive orientado al mercado local"],
        featured: false,
        order: 9,
        seo: { description: "Mercadillo.pe es una plataforma privada de delivery y gestión para restaurantes." },
      },
      {
        id: "project-kc-automotriz",
        slug: "kc-automotriz",
        title: "KC Automotriz",
        excerpt: "Catálogo de vehículos con filtros, cotizador de cuotas y un panel para administrar inventario y contactos.",
        body: "## Una vitrina que también opera\n\nKC Automotriz combina un catálogo visual para compradores con herramientas de gestión para el equipo. Los vehículos pueden filtrarse por marca, modelo, kilometraje y condición.\n\n## Conversión y administración\n\nEl cotizador ayuda a proyectar cuotas, mientras los puntos de contacto registran interesados. Un panel privado organiza inventario, marcas, promociones y seguimiento.\n\n## Estado\n\nEl repositorio y la demostración permanecen privados porque el proyecto corresponde a un cliente.",
        category: "Cliente",
        type: "Sitio y panel privados",
        role: "Diseño y desarrollo full-stack",
        year: "2026",
        stack: ["Next.js", "React", "Supabase", "PostgreSQL", "CSS"],
        outcomes: ["Catálogo con filtrado avanzado", "Cotizador interactivo de financiamiento", "Panel para inventario y prospectos"],
        featured: false,
        order: 10,
        seo: { description: "KC Automotriz combina catálogo, cotizador y gestión privada de inventario de vehículos." },
      },
      {
        id: "project-pachas-web",
        slug: "pachas-cafe-web",
        title: "Pacha’s Café",
        excerpt: "Sistema local de ventas con productos, clientes, compras, caja e inventario para la operación del café.",
        body: "## Operación completa\n\nEl proyecto reúne ventas, productos, variantes, clientes, proveedores, compras, caja y fidelización en un flujo pensado para la operación diaria de Pacha’s Café.\n\n## Arquitectura local\n\nUna interfaz PHP consume una API Spring Boot con persistencia H2. El entorno incluye datos de demostración y perfiles de administración para comprobar el recorrido completo sin depender de servicios externos.\n\n## Estado\n\nEl sistema se ejecuta de forma local y el repositorio permanece privado por contener lógica de negocio del cliente.",
        category: "Cliente",
        type: "Sistema local privado",
        role: "Desarrollo full-stack",
        year: "2026",
        stack: ["PHP", "Spring Boot", "Java", "H2", "Docker"],
        outcomes: ["Ventas e inventario conectados", "Compras, caja y fidelización integradas", "Entorno local reproducible con datos de demostración"],
        featured: false,
        order: 11,
        seo: { description: "Sistema privado de ventas, inventario, compras y caja desarrollado para Pacha’s Café." },
      },
      {
        id: "project-misterio-maria",
        slug: "misterio-maria",
        title: "El misterio de María del Carmen",
        excerpt: "Experiencia personalizada para descubrir un regalo mediante pistas, una teoría y una clave secreta.",
        body: "## Un regalo convertido en recorrido\n\nLa experiencia presenta cuatro pistas y permite construir una teoría antes de intentar revelar el regalo. El progreso se conserva para continuar más tarde.\n\n## Privacidad desde la arquitectura\n\nLa respuesta y la fotografía no forman parte de la carga inicial. El Worker solo las entrega cuando valida la clave en el servidor, y D1 conserva borradores e intentos sin exponer el contenido protegido.\n\n## Acceso\n\nLa experiencia está desplegada, pero su contenido final requiere la clave de la persona destinataria.",
        category: "Regalo digital",
        type: "Experiencia web privada",
        role: "Concepto, diseño y desarrollo",
        year: "2026",
        stack: ["Next.js", "React", "TypeScript", "Vinext", "Cloudflare Workers", "D1"],
        outcomes: ["Recorrido interactivo de cuatro pistas", "Respuesta y fotografía protegidas en el servidor", "Borradores recuperables entre sesiones"],
        liveUrl: "https://regalomaria04.withered-hat-79c9.workers.dev",
        featured: false,
        order: 12,
        seo: { description: "Experiencia web privada para descubrir un regalo mediante pistas y una clave secreta." },
      },
      {
        id: "project-cumpleanos",
        slug: "cumpleanos",
        title: "Cumpleaños",
        excerpt: "Experiencias privadas de cumpleaños con contenido personalizado, acceso por contraseña y medios protegidos.",
        body: "## Un formato reutilizable y personal\n\nCada persona recibe una ruta y una edición visual propia. El contenido se organiza en un registro privado para incorporar nuevos cumpleaños sin duplicar la aplicación.\n\n## Protección\n\nLas credenciales y sesiones viven en D1; las imágenes privadas permanecen en R2. La portada pública responde como una página no encontrada y solo las rutas destinadas exponen el inicio de sesión.\n\n## Estado\n\nEl proyecto está desplegado, pero no ofrece una demostración pública porque todo el contenido está dirigido a personas concretas.",
        category: "Experiencia digital",
        type: "Aplicación web privada",
        role: "Diseño, desarrollo y operación",
        year: "2026",
        stack: ["React", "TypeScript", "Vite", "Chakra UI", "Cloudflare Workers", "D1", "R2"],
        outcomes: ["Ediciones visuales por persona y año", "Sesiones protegidas con credenciales", "Medios privados fuera del bundle público"],
        featured: false,
        order: 13,
        seo: { description: "Sistema privado para crear experiencias de cumpleaños personalizadas y proteger sus medios." },
      },
      {
        id: "project-seas-venta",
        slug: "seas-venta",
        title: "SEAS Venta",
        excerpt: "Aplicación móvil colaborativa para ventas, caja, inventario, clientes y operación de tiendas de ropa.",
        body: "## Gestión desde el teléfono\n\nSEAS Venta lleva el punto de venta y la operación diaria de una tienda a una aplicación Flutter: catálogo, variantes, clientes, compras, caja, devoluciones, promociones y reportes.\n\n## Trabajo sin conexión\n\nEl catálogo y los clientes pueden mantenerse en caché; las ventas creadas sin red entran en una cola local y se sincronizan al recuperar conectividad.\n\n## Estado\n\nEs un desarrollo colaborativo en curso. El repositorio y los servicios de datos permanecen privados.",
        category: "Proyecto colaborativo",
        type: "Aplicación móvil privada",
        role: "Desarrollo de producto en equipo",
        year: "2026",
        stack: ["Flutter", "Dart", "GetX", "Supabase", "Hive", "Firebase"],
        outcomes: ["Punto de venta y caja móvil", "Inventario, clientes y reportes integrados", "Cola offline para ventas pendientes"],
        featured: false,
        order: 14,
        seo: { description: "SEAS Venta es una aplicación Flutter privada para gestionar ventas y operación de tiendas de ropa." },
      },
      {
        id: "project-municipalidad-rioja",
        slug: "municipalidad-de-rioja",
        title: "Municipalidad de Rioja",
        excerpt: "Propuesta para modernizar la presencia digital y facilitar información ciudadana.",
        body: "Concepto web orientado a ordenar información municipal y simplificar su consulta desde distintos dispositivos.",
        category: "Archivo de propuestas",
        type: "Propuesta web",
        role: "Diseño de interfaz",
        year: "2022",
        stack: ["Diseño web", "Arquitectura de información"],
        outcomes: ["Información organizada por necesidades", "Propuesta adaptable"],
        featured: false,
        order: 15,
        seo: {},
      },
      {
        id: "project-discord",
        slug: "discord",
        title: "Comunidades en Discord",
        excerpt: "Configuración y moderación de espacios digitales con roles y canales comprensibles.",
        body: "Experiencia organizando comunidades, permisos, canales y automatizaciones para mantener espacios digitales claros y seguros.",
        category: "Archivo",
        type: "Comunidades",
        role: "Configuración y moderación",
        year: "2018–2025",
        stack: ["Discord", "Bots", "Moderación"],
        outcomes: ["Roles y permisos claros", "Canales organizados", "Automatización de tareas repetitivas"],
        featured: false,
        order: 16,
        seo: {},
      },
      {
        id: "project-nieto-hub",
        slug: "nieto-hub",
        title: "NIETO Hub",
        excerpt: "Portafolio público de los productos digitales desarrollados para NIETO.",
        body: "## Un punto de entrada común\n\nNIETO Hub reúne en una sola página los productos digitales desarrollados para la empresa, con acceso directo a cada plataforma y fichas públicas de proyecto.\n\n## Contenido seguro y actualizable\n\nLas fichas describen objetivos, tecnologías y resultados sin exponer repositorios, credenciales ni datos internos. El contenido publicado se administra desde Second Brain y puede incorporar nuevos proyectos sin reconstruir el sitio.",
        category: "Cliente",
        type: "Portafolio web",
        role: "Diseño, arquitectura y desarrollo",
        year: "2026",
        stack: ["React", "TypeScript", "Vite", "Chakra UI", "Cloudflare Workers"],
        outcomes: ["Productos de NIETO reunidos en una sola vista", "Detalles públicos sin exponer información interna", "Contenido desacoplado y preparado para crecer"],
        liveUrl: "https://nieto.velaarturo.com",
        featured: false,
        order: 17,
        seo: { description: "NIETO Hub reúne los productos digitales desarrollados para NIETO en un portafolio público y seguro." },
      },
      {
        id: "project-coffee",
        slug: "coffee",
        title: "Cafetero",
        excerpt: "Directorio y pasaporte de cafeterías del Perú con mapas, fichas verificables y registro de visitas.",
        body: "## Descubrir cafeterías con información trazable\n\nCafetero organiza 41 locales del pasaporte cafetero 2026.2 en un directorio con búsqueda, mapa y fichas renderizadas en servidor. El catálogo conserva la fuente y el estado de revisión sin inventar reseñas, puntuaciones ni imágenes.\n\n## Un producto para visitantes y locales\n\nAdemás de la consulta pública, el sistema incorpora cuentas protegidas, pasaporte de visitas, códigos QR, solicitudes de representantes y flujos de moderación con permisos explícitos.\n\n## Estado\n\nLa versión pública de pruebas permite recorrer el directorio y el mapa. Las funciones de cuenta y administración continúan sujetas a la aceptación final con proveedores y dispositivos reales.",
        category: "Producto personal",
        type: "Aplicación web en pruebas",
        role: "Producto, investigación y desarrollo",
        year: "2026",
        stack: ["React Router", "React", "TypeScript", "Chakra UI", "Cloudflare Workers", "D1", "R2", "MapLibre"],
        outcomes: ["41 cafeterías con fuentes trazables", "Mapa y fichas SSR para consulta pública", "Pasaporte, visitas y gestión con permisos"],
        liveUrl: "https://cafetero.velaarturo.com",
        repoUrl: "https://github.com/ArturoVela/coffee",
        featured: true,
        order: 18,
        seo: { description: "Cafetero es un directorio y pasaporte de cafeterías del Perú con mapas, fichas verificables y registro de visitas." },
      },
      {
        id: "project-explora",
        slug: "explora-san-martin",
        title: "Explora San Martín",
        excerpt: "Mapa turístico con 164 fichas de fuentes oficiales, contenido verificable y un pasaporte personal.",
        body: "## Turismo con fuentes visibles\n\nExplora San Martín reúne 155 registros de MINCETUR y nueve fichas municipales adicionales en un mapa que distingue claramente la información verificada, las coordenadas pendientes y la disponibilidad de fotografías.\n\n## Recorrido público y personal\n\nLas fichas se renderizan en servidor para ofrecer una consulta rápida y rastreable. Quien inicia sesión puede construir un pasaporte personal, mientras los flujos editoriales mantienen permisos y medios separados.\n\n## Arquitectura\n\nReact Router sirve la experiencia SSR desde Cloudflare Workers; D1 conserva el catálogo y las identidades, R2 almacena medios y MapLibre presenta el territorio con atribución abierta.",
        category: "Turismo digital",
        type: "Aplicación web",
        role: "Producto, investigación y desarrollo",
        year: "2026",
        stack: ["React Router", "React", "TypeScript", "Chakra UI", "Cloudflare Workers", "D1", "R2", "MapLibre"],
        outcomes: ["164 lugares documentados con fuentes", "Mapa y fichas SSR accesibles", "Pasaporte personal y flujo editorial protegido"],
        liveUrl: "https://explora.velaarturo.com",
        repoUrl: "https://github.com/ArturoVela/explora",
        featured: true,
        order: 19,
        seo: { description: "Explora San Martín reúne lugares turísticos verificables en un mapa público con fichas SSR y pasaporte personal." },
      },
      {
        id: "project-ruleta",
        slug: "ruleta",
        title: "Ruleta",
        excerpt: "Una ruleta local-first para decidir entre opciones, elegir varios ganadores y compartir sesiones editables.",
        body: "## Decidir sin fricción\n\nRuleta permite pegar o editar opciones, asignar pesos, ocultarlas, elegir varios ganadores y decidir si una opción se repite o se elimina después de ganar. La selección usa Web Crypto y evita sesgos por módulo.\n\n## Local o compartida\n\nEl modo local funciona sin cuenta y queda disponible sin conexión después de la primera carga. Cuando se comparte, D1 guarda una copia independiente y entrega enlaces separados para participar y editar.\n\n## Accesibilidad\n\nLa experiencia admite teclado, movimiento reducido, historial, deshacer y una organización por pestañas en pantallas pequeñas.",
        category: "Herramienta pública",
        type: "Aplicación web",
        role: "Diseño y desarrollo integral",
        year: "2026",
        stack: ["React", "TypeScript", "Vite", "Chakra UI", "Cloudflare Workers", "D1", "Web Crypto"],
        outcomes: ["Selección uniforme o ponderada", "Uso local disponible sin conexión", "Enlaces separados para participar y editar"],
        liveUrl: "https://ruleta.velaarturo.com",
        repoUrl: "https://github.com/ArturoVela/ruleta",
        featured: false,
        order: 20,
        seo: { description: "Ruleta ayuda a decidir entre opciones con pesos, varios ganadores, modo offline y enlaces seguros para compartir." },
      },
      {
        id: "project-llevamos",
        slug: "llevamos",
        title: "Llevamos",
        excerpt: "Coordina qué aporta cada persona a una reunión sin crear cuentas ni compartir contraseñas.",
        body: "## Cada quien pone algo\n\nLlevamos organiza comida, bebidas, objetos y responsabilidades para una reunión. El anfitrión crea la lista, comparte la invitación y cada participante elige o propone su aporte.\n\n## Acceso simple y separado\n\nEl producto evita las cuentas: cada reunión tiene enlaces y permisos específicos para organización y participación. Los datos viven en D1 y las escrituras pasan por validación, límites y Turnstile donde corresponde.\n\n## Una interfaz para el momento real\n\nEl tablero se adapta a móvil, muestra el progreso del grupo y se actualiza al volver a la pestaña o después de guardar, sin mantener conexiones permanentes.",
        category: "Herramienta pública",
        type: "Aplicación web",
        role: "Diseño y desarrollo integral",
        year: "2026",
        stack: ["React", "TypeScript", "Vite", "Chakra UI", "Cloudflare Workers", "D1", "Turnstile"],
        outcomes: ["Coordinación sin cuentas", "Permisos separados por invitación", "Tablero responsive con progreso compartido"],
        liveUrl: "https://llevamos.velaarturo.com",
        repoUrl: "https://github.com/ArturoVela/llevamos",
        featured: false,
        order: 21,
        seo: { description: "Llevamos coordina comida, objetos y responsabilidades de una reunión sin cuentas ni contraseñas." },
      },
      {
        id: "project-horas",
        slug: "horas",
        title: "Horas",
        excerpt: "Compara zonas horarias, encuentra coincidencias laborales y comparte un instante sin llamadas externas.",
        body: "## El mismo instante, explicado para cada ciudad\n\nHoras compara hasta ocho zonas IANA sobre una sola línea temporal. La primera zona define la referencia y el sistema muestra cambios de día, offsets y transiciones de horario de verano sin usar tablas fijas.\n\n## Coincidencias de trabajo\n\nCada zona puede tener su propio horario laboral, incluidos turnos nocturnos. La aplicación calcula la intersección y permite compartir el instante, las zonas y la configuración mediante una URL validada.\n\n## Privacidad\n\nTodas las conversiones se realizan con Intl y Luxon en el navegador; no hay API, cuentas, base de datos ni analítica.",
        category: "Herramienta pública",
        type: "Aplicación web",
        role: "Diseño y desarrollo integral",
        year: "2026",
        stack: ["React", "TypeScript", "Vite", "Chakra UI", "Luxon", "Cloudflare Workers"],
        outcomes: ["Comparación de hasta ocho zonas", "Coincidencias para horarios laborales", "Enlaces compartibles sin almacenar datos"],
        liveUrl: "https://horas.velaarturo.com",
        repoUrl: "https://github.com/ArturoVela/horas",
        featured: false,
        order: 22,
        seo: { description: "Horas compara zonas horarias, calcula coincidencias laborales y comparte instantes desde el navegador." },
      },
      {
        id: "project-qr",
        slug: "qr",
        title: "QR",
        excerpt: "Genera, verifica y lee códigos QR localmente, con personalización y exportación segura.",
        body: "## Crear y comprobar en el mismo lugar\n\nQR genera códigos para enlaces, texto, Wi-Fi, correo, teléfono, SMS, contactos, calendario y coordenadas. Permite ajustar colores, corrección, margen, módulos y logo antes de exportar PNG o SVG.\n\n## Verificación antes de descargar\n\nCada imagen renderizada se vuelve a leer localmente para bloquear resultados ilegibles o ambiguos. El lector admite imágenes y cámara con BarcodeDetector o un fallback WebAssembly servido desde el mismo dominio.\n\n## Privacidad\n\nEl contenido vive solo en memoria: no se guarda en el navegador, no se añade a la URL y nunca se envía a un servidor.",
        category: "Herramienta pública",
        type: "Aplicación web",
        role: "Diseño y desarrollo integral",
        year: "2026",
        stack: ["React", "TypeScript", "Vite", "Chakra UI", "WebAssembly", "Cloudflare Workers"],
        outcomes: ["Generación para nueve tipos de contenido", "Verificación local antes de exportar", "Lectura por imagen o cámara sin subir datos"],
        liveUrl: "https://qr.velaarturo.com",
        repoUrl: "https://github.com/ArturoVela/qr",
        featured: false,
        order: 23,
        seo: { description: "QR genera, verifica y lee códigos personalizados localmente sin almacenar ni enviar su contenido." },
      },
      {
        id: "project-pdf",
        slug: "pdf",
        title: "PDF",
        excerpt: "Organiza, transforma y convierte documentos PDF directamente en el navegador, sin subir archivos.",
        body: "## Una caja de herramientas local\n\nPDF permite unir, separar, extraer, eliminar, rotar y numerar páginas. También convierte imágenes a PDF, exporta páginas como PNG y muestra los metadatos principales del documento.\n\n## Diseñada para archivos sensibles\n\nLos documentos y sus nombres permanecen únicamente en memoria. Un Web Worker del navegador ejecuta las transformaciones con tiempos y límites explícitos; no existen rutas de subida, bases de datos ni almacenamiento remoto.\n\n## Control y accesibilidad\n\nEl orden admite arrastre, teclado y rangos de selección. Un historial de cambios permite deshacer antes de descargar el resultado.",
        category: "Herramienta pública",
        type: "Aplicación web",
        role: "Diseño y desarrollo integral",
        year: "2026",
        stack: ["React", "TypeScript", "Vite", "Chakra UI", "PDF.js", "pdf-lib", "Web Workers"],
        outcomes: ["Ocho operaciones de organización y conversión", "Procesamiento íntegramente local", "Reordenamiento accesible e historial de cambios"],
        liveUrl: "https://pdf.velaarturo.com",
        repoUrl: "https://github.com/ArturoVela/pdf",
        featured: false,
        order: 24,
        seo: { description: "PDF permite unir, separar, rotar, numerar y convertir documentos localmente sin subir archivos." },
      },
      {
        id: "project-foto",
        slug: "foto",
        title: "Foto",
        excerpt: "Comprime, redimensiona, recorta y convierte imágenes en lotes sin sacarlas del dispositivo.",
        body: "## Una mesa de luz en el navegador\n\nFoto permite redimensionar, recortar, rotar, voltear y convertir JPG, PNG y WebP. La comparación antes/después, los presets y el procesamiento por lotes ayudan a revisar cada resultado antes de descargarlo.\n\n## Privacidad comprobable\n\nLos bytes y nombres de las imágenes no salen del dispositivo. Un Web Worker procesa cada tarea, elimina metadatos personales y crea el ZIP localmente; al borrar se cancelan trabajos y se revocan las URLs temporales.\n\n## Límites claros\n\nLa aplicación valida firmas, dimensiones, memoria estimada y formato real para responder con errores explicativos en lugar de producir archivos dudosos.",
        category: "Herramienta pública",
        type: "Aplicación web",
        role: "Diseño y desarrollo integral",
        year: "2026",
        stack: ["React", "TypeScript", "Vite", "Chakra UI", "Canvas", "Web Workers", "Cloudflare Workers"],
        outcomes: ["Edición y conversión por lotes", "Eliminación local de metadatos personales", "Comparación visual antes de descargar"],
        liveUrl: "https://foto.velaarturo.com",
        repoUrl: "https://github.com/ArturoVela/foto",
        featured: false,
        order: 25,
        seo: { description: "Foto comprime, redimensiona, recorta y convierte imágenes por lotes sin subirlas a un servidor." },
      },
      {
        id: "project-cuando",
        slug: "cuando",
        title: "Cuando",
        excerpt: "Encuestas para encontrar una fecha de reunión, comparar disponibilidad y coordinar sin cuentas.",
        body: "## Encontrar el momento en común\n\nCuando permite proponer fechas con zona horaria, invitar participantes y responder Sí, Tal vez o No. Los resultados priorizan la mayor disponibilidad sin confundir una ausencia de voto con una respuesta negativa.\n\n## Enlaces con responsabilidades distintas\n\nLa encuesta usa identificadores públicos y tokens privados separados para administración y edición. Los secretos viajan en el fragmento de la URL y D1 conserva únicamente sus hashes.\n\n## Operación completa\n\nEl organizador puede editar, retirar y recuperar alternativas, exportar CSV, consultar el historial y eliminar permanentemente la encuesta con confirmación.",
        category: "Herramienta pública",
        type: "Aplicación web",
        role: "Diseño y desarrollo integral",
        year: "2026",
        stack: ["React", "TypeScript", "Vite", "Chakra UI", "Cloudflare Workers", "D1", "Temporal"],
        outcomes: ["Disponibilidad Sí, Tal vez y No", "Zonas horarias con validación DST", "Enlaces privados separados y auditables"],
        liveUrl: "https://cuando.velaarturo.com",
        repoUrl: "https://github.com/ArturoVela/cuando",
        featured: false,
        order: 26,
        seo: { description: "Cuando crea encuestas de disponibilidad con zonas horarias y enlaces privados, sin exigir cuentas." },
      },
      {
        id: "project-cotiza",
        slug: "cotiza",
        title: "Cotiza",
        excerpt: "Crea cotizaciones profesionales y borradores de contratos con cálculos precisos y exportación PDF.",
        body: "## Del alcance al documento final\n\nCotiza guía la creación de propuestas con emisor, cliente, conceptos, descuentos, impuestos, pagos recurrentes, hitos y condiciones. También convierte una cotización en un borrador de contrato editable.\n\n## Trabajo local por defecto\n\nEl historial, catálogo, perfil, logo y borradores permanecen en el navegador. Solo una acción explícita guarda una copia en D1 para compartirla mediante enlaces separados de lectura y edición.\n\n## Cálculos y formatos\n\nDecimal.js mantiene importes y redondeos por moneda. La aplicación genera PDF con fuentes incrustadas, permite imprimir, exportar JSON y preparar un mensaje de WhatsApp para revisión manual.",
        category: "Herramienta profesional",
        type: "Aplicación web",
        role: "Producto, diseño y desarrollo",
        year: "2026",
        stack: ["React", "TypeScript", "Vite", "Chakra UI", "Decimal.js", "Cloudflare Workers", "D1"],
        outcomes: ["Cotizaciones y contratos en un mismo flujo", "Cálculos decimales para siete monedas", "Guardado local o compartido con consentimiento"],
        liveUrl: "https://cotiza.velaarturo.com",
        repoUrl: "https://github.com/ArturoVela/cotiza",
        featured: false,
        order: 27,
        seo: { description: "Cotiza crea cotizaciones profesionales y borradores de contratos con cálculos precisos, PDF y guardado opcional." },
      },
      {
        id: "project-color",
        slug: "color",
        title: "Color",
        excerpt: "Estudio cromático para convertir, combinar, evaluar y exportar colores, paletas y gradientes.",
        body: "## Un laboratorio cromático completo\n\nColor reúne selector, conversor, armonías, paletas, gradientes, mezclas, contraste WCAG, nombres CSS y tablas de referencia en una sola suite. También extrae colores desde imágenes procesadas localmente.\n\n## Modelos con precisión explícita\n\nCulori realiza conversiones entre HEX, RGB, HSL, HSV, HWB, LAB, LCH, OKLAB, OKLCH y una aproximación CMYK. La interfaz distingue espacios de color, gamut y límites de cada exportación.\n\n## Sin servidor de aplicación\n\nLas imágenes nunca se almacenan remotamente; favoritos, historial y paletas permanecen en el navegador. Los enlaces compartidos contienen únicamente colores HEX validados.",
        category: "Herramienta de diseño",
        type: "Aplicación web",
        role: "Diseño y desarrollo integral",
        year: "2026",
        stack: ["React", "TypeScript", "Vite", "Chakra UI", "Culori", "Canvas", "Cloudflare Workers"],
        outcomes: ["Diez herramientas cromáticas integradas", "Conversión entre espacios perceptuales y CSS", "Paletas y gradientes exportables sin subir imágenes"],
        liveUrl: "https://color.velaarturo.com",
        repoUrl: "https://github.com/ArturoVela/color",
        featured: false,
        order: 28,
        seo: { description: "Color es una suite para convertir, combinar, comprobar y exportar colores, paletas y gradientes." },
      },
    ],
    articles: [
      {
        id: "article-rice-visual-analysis",
        slug: "tesis-arroz-29-04-2025",
        title: "Análisis visual de factores que afectan el rendimiento del arroz",
        excerpt: "Segundo avance de investigación: observaciones de campo y entrevista con un especialista agrónomo.",
        body: "En esta segunda fase incorporé la experiencia del ingeniero agrónomo Ever Ramírez Rojas para complementar el análisis técnico con observaciones de campo.\n\n## Preguntas de investigación\n\nLa entrevista explora qué señales visuales permiten anticipar un buen rendimiento, qué factores son determinantes y en qué etapa del cultivo resulta más viable realizar la evaluación.\n\nEl objetivo de este avance es contrastar las variables del modelo con conocimiento práctico antes de ajustar la propuesta predictiva.",
        category: "Investigación",
        tags: ["Arroz", "Agronomía", "Datos"],
        publishedAt: "2025-04-29",
        readingMinutes: 6,
        cover: { src: "/assets/images/blog/blog-details1-tesis-29-04-2025.webp", alt: "Análisis visual de un cultivo de arroz", width: 1920, height: 850 },
        seo: {},
      },
      {
        id: "article-rice-tcn",
        slug: "tesis-arroz-22-04-2025",
        title: "Modelo predictivo de rendimiento de arroz con datos satelitales y climáticos",
        excerpt: "Un estudio sobre redes convolucionales temporales y datos multiespectrales aplicados a agricultura.",
        body: "La predicción temprana del rendimiento agrícola es una herramienta importante para la planificación. Este estudio revisa un método que combina redes convolucionales temporales con datos multiespectrales.\n\n## Datos utilizados\n\nEl trabajo considera índices de vegetación MODIS, variables climáticas y datos históricos de rendimiento entre 2012 y 2019.\n\n## Aspectos del modelo\n\n- Analiza múltiples variables de manera conjunta.\n- Identifica relaciones temporales.\n- Compara el error de predicción mediante MAE, RMSE y R².\n\nEl avance sirve como base técnica para adaptar el enfoque a información agrícola regional.",
        category: "Investigación",
        tags: ["Machine learning", "Satélites", "Agricultura"],
        publishedAt: "2025-04-22",
        readingMinutes: 8,
        cover: { src: "/assets/images/blog/blog-details1-tesis-22-04-2025.webp", alt: "Datos satelitales aplicados al cultivo de arroz", width: 1920, height: 850 },
        seo: {},
      },
      {
        id: "article-discord-business",
        slug: "discord-para-negocios",
        title: "Cómo usar Discord para tu negocio o comunidad online",
        excerpt: "Canales, roles, bots y criterios básicos para construir una comunidad organizada.",
        body: "Discord también puede servir como espacio de soporte, coordinación y comunidad para un negocio. La diferencia está en diseñar una estructura que las personas entiendan.\n\n## Un punto de partida\n\n- Define canales por propósito, no por ocurrencia.\n- Separa permisos de moderación y participación.\n- Automatiza tareas repetitivas con bots bien delimitados.\n- Documenta las reglas donde la comunidad pueda encontrarlas.\n\nUna comunidad sana necesita más que herramientas: requiere expectativas claras, moderación consistente y canales para escuchar a sus miembros.",
        category: "Comunidades",
        tags: ["Discord", "Moderación", "Comunidad"],
        publishedAt: "2025-04-21",
        readingMinutes: 4,
        cover: { src: "/assets/images/blog/blog-details1-discord.webp", alt: "Interfaz de una comunidad organizada en Discord", width: 1920, height: 850 },
        seo: {},
      },
    ],
  },
};
