import { FALLBACK_ENVELOPE } from "@/content/fallback";
import type { PortfolioEnvelope, ProjectContent } from "@/types/content";

type ProjectCopy = Pick<ProjectContent, "slug" | "title" | "excerpt" | "body" | "category" | "type" | "role" | "outcomes"> & { seoDescription: string };

const projectCopies: ProjectCopy[] = [
  { slug: "hub", title: "Hub", excerpt: "39 everyday tools in one fast, modular, local-first SPA.", body: "## Challenge\n\nBring calculation, text, design, productivity, and development utilities together without turning the home page into a heavy bundle.\n\n## Solution\n\nA React and Vite architecture loads each tool on demand. Sensitive work stays in the browser whenever possible; the Worker handles only features that require an API or persistence.\n\n## Approach\n\nOne catalog drives routes, search, and relationships. Favorites, recent activity, and preferences remain local, while D1 stores only short links and rankings.", category: "Independent product", type: "Web application", role: "End-to-end design and development", outcomes: ["39 tools across 11 categories", "Local processing for sensitive files and data", "On-demand loading for every tool"], seoDescription: "Hub brings 39 web tools together in a local-first SPA built with React, Vite, and Cloudflare Workers." },
  { slug: "un-ramito", title: "Un ramito", excerpt: "An experience for creating and sharing virtual bouquets with private messages.", body: "## A small experience with real privacy\n\nSomeone designs a bouquet, writes a message, and shares a link. The message is encrypted in the browser before leaving the device.\n\n## Architecture\n\nCloudflare D1 keeps only the encrypted envelope for 90 days. The key travels in the URL fragment, which is never sent to the server.", category: "Digital experience", type: "Web application", role: "Product, design, and development", outcomes: ["In-browser encryption", "Private links that are easy to share", "Automatic 90-day expiration"], seoDescription: "Un ramito lets people design and share virtual bouquets with messages encrypted in the browser." },
  { slug: "security-lab", title: "Security Lab", excerpt: "Private lab for comparing four generations of audits and their test environments.", body: "## Learn by comparison\n\nThe lab organizes four audit versions alongside their test environments. A matrix makes changes between the original implementation, a hardened version, and later replacements visible.\n\n## Clear boundaries\n\nModules are designed for owned, academic, or explicitly authorized systems. Access is private, and general-purpose utilities moved to Hub.", category: "Applied security", type: "Private web lab", role: "Architecture and development", outcomes: ["Four generations compared", "Eight modules organized in one matrix", "General utilities separated into Hub"], seoDescription: "Arturo Vela's private lab for comparing audit generations and test environments." },
  { slug: "cana-wasky", title: "Caña Wasky", excerpt: "Excel system for organizing sales, inventory, and reporting for a food business.", body: "## Context\n\nCaña Wasky needed its commercial controls in one tool the team could understand and use every day.\n\n## Solution\n\nThe work structured sales and inventory in Excel, automated reporting, and provided an interface designed for daily operations.\n\n## Rationale\n\nIt favored technology already available to the team instead of imposing a platform that would be harder to maintain.", category: "Client", type: "Sales system", role: "Analysis and development", outcomes: ["Sales and inventory in one flow", "Automated reports", "Operations built on a familiar tool"], seoDescription: "Sales, inventory, and reporting system created for Caña Wasky." },
  { slug: "porta", title: "Porta", excerpt: "Professional portfolio with decoupled content, edge SEO, and protected comments.", body: "## Portfolio as a product\n\nPorta brings projects, articles, and profile content into a fast SPA while serving useful metadata and HTML responses to search engines from the Worker.\n\n## Architecture\n\nOne Cloudflare Worker serves the app, content API, sitemap, and feed. A private Second Brain connection supplies publications and media; cache and backup layers keep the site available when that origin fails.\n\n## Operations\n\nComments live in a separate D1 database and Turnstile protects submissions. The portfolio code is public so the architecture can be verified.", category: "Independent product", type: "Web portfolio", role: "Design, architecture, and development", outcomes: ["Decoupled content with local backup", "Edge-generated SEO, sitemap, and feed", "Public repository and verifiable deployment"], seoDescription: "Porta is Arturo Vela's portfolio, built with React, Vite, Chakra UI, and Cloudflare Workers." },
  { slug: "second-brain", title: "Second Brain", excerpt: "Personal space for capturing, connecting, and reviewing information, tasks, files, and projects.", body: "## A personal system, not a collection of screens\n\nSecond Brain combines capture, universal objects, rich editing, search, relationships, calendar, and review in one private space.\n\n## Cloudflare-first architecture\n\nD1 holds relational data and search; R2 stores versioned files; Queues handles indexing and extraction; Cloudflare Access protects remote environments.\n\n## Integration\n\nIt also acts as this portfolio's private editorial source through a versioned contract and a Worker-to-Worker Service Binding.", category: "Independent product", type: "Private web system", role: "Product, architecture, and development", outcomes: ["Capture, search, and review in one system", "Private files with versions", "Decoupled publishing to Porta"], seoDescription: "Second Brain is a private personal system for knowledge, planning, files, and content publishing." },
  { slug: "db-nieto", title: "DB Nieto", excerpt: "Business intelligence that preserves six historical fiscal years and turns them into queryable dashboards.", body: "## From operational archive to queryable source\n\nDB Nieto preserves commercial information from six fiscal years stored in Visual FoxPro and presents it in a protected BI application.\n\n## Auditable migration\n\nOriginal DBF files remain the traceable source. An idempotent generator prepares D1 loads, while React and Chakra UI present indicators by period.\n\n## Access\n\nThe app is online, but Cloudflare Access restricts it to authorized identities because it works with internal information.", category: "Internal system", type: "Private dashboard", role: "Migration, architecture, and development", outcomes: ["Six fiscal years brought together", "Idempotent migration from DBF", "Protected access without exposing source files"], seoDescription: "DB Nieto turns six years of Visual FoxPro history into a private BI application on Cloudflare." },
  { slug: "nieto-import", title: "Nieto Import", excerpt: "Internal system that centralizes labels, workflows, documentation, and administrative tools.", body: "## Problem\n\nNieto Import and Agromaf used separate administrative utilities for labels, documents, corporate signatures, and management forms. That fragmentation made tools harder to find and a shared workflow harder to sustain.\n\n## Key decisions\n\nThe solution brings those processes into one responsive interface with permissions, search, and routes shaped around daily work. Operational information and source code remain private.\n\n## Process\n\nThe product is organized around concrete jobs: generate and print labels, browse departmental documentation, prepare signatures, and complete forms. The same system runs on the web and through a mobile wrapper.\n\n## Results and scope\n\nIt now centralizes administrative tools for two companies and limits access to authorized accounts. This case documents capabilities without showing private operational data or screens.", category: "Internal system", type: "Private web application", role: "Full-stack development and product evolution", outcomes: ["Centralized administrative tools", "Support for two companies", "Web experience and mobile wrapper"], seoDescription: "Nieto Import is a private application for labels, documentation, and administrative workflows." },
  { slug: "mercadillo-pe", title: "Mercadillo.pe", excerpt: "Delivery and restaurant management platform with catalog, orders, and administrative operations.", body: "## Collaborative product\n\nMercadillo.pe connects customers, restaurants, and delivery in a responsive experience covering discovery, menus, cart, checkout, and order tracking.\n\n## Operations\n\nBeyond the public journey, it includes merchant management, inventory, promotions, communications, and administrative tools on Supabase.\n\n## Status\n\nThe project and current deployment are private; this case documents scope without exposing code or data.", category: "Collaborative project", type: "Private web platform", role: "Team full-stack development", outcomes: ["Complete catalog and order flow", "Merchant and administration modules", "Responsive design for the local market"], seoDescription: "Mercadillo.pe is a private delivery and restaurant-management platform." },
  { slug: "kc-automotriz", title: "KC Automotriz", excerpt: "Vehicle catalog with filters, payment estimator, and an inventory and lead management panel.", body: "## A storefront that also operates\n\nKC Automotriz combines a visual catalog for buyers with team management tools. Vehicles can be filtered by make, model, mileage, and condition.\n\n## Conversion and administration\n\nThe estimator projects installments, contact points record interested buyers, and a private panel manages inventory, makes, promotions, and follow-up.\n\n## Status\n\nThe repository and demo remain private because this is client work.", category: "Client", type: "Private site and dashboard", role: "Design and full-stack development", outcomes: ["Advanced catalog filtering", "Interactive financing estimator", "Inventory and lead dashboard"], seoDescription: "KC Automotriz combines a catalog, estimator, and private vehicle inventory management." },
  { slug: "pachas-cafe-web", title: "Pacha’s Café", excerpt: "Local sales system for products, customers, purchases, cash register, and inventory.", body: "## Complete operations\n\nThe project brings sales, products, variants, customers, suppliers, purchases, cash register, and loyalty into one flow for Pacha's Café.\n\n## Local architecture\n\nA PHP interface consumes a Spring Boot API backed by H2. Demo data and administrator profiles make the full journey reproducible without external services.\n\n## Status\n\nThe system runs locally and the repository remains private because it contains client business logic.", category: "Client", type: "Private local system", role: "Full-stack development", outcomes: ["Connected sales and inventory", "Integrated purchases, cash register, and loyalty", "Reproducible local environment with demo data"], seoDescription: "Private sales, inventory, purchasing, and cash-register system developed for Pacha's Café." },
  { slug: "misterio-maria", title: "The mystery of María del Carmen", excerpt: "Personalized experience for discovering a gift through clues, a theory, and a secret key.", body: "## A gift turned into a journey\n\nThe experience presents four clues and lets the recipient build a theory before trying to reveal the gift. Progress is saved for later.\n\n## Privacy in the architecture\n\nThe answer and photograph are absent from the initial bundle. The Worker sends them only after server-side key validation, while D1 stores drafts and attempts without exposing protected content.\n\n## Access\n\nThe experience is deployed, but the final content requires the recipient's key.", category: "Digital gift", type: "Private web experience", role: "Concept, design, and development", outcomes: ["Interactive four-clue journey", "Server-protected answer and photograph", "Recoverable drafts across sessions"], seoDescription: "Private web experience for discovering a gift through clues and a secret key." },
  { slug: "cumpleanos", title: "Birthdays", excerpt: "Private birthday experiences with personalized content, password access, and protected media.", body: "## A reusable, personal format\n\nEach person receives a route and visual edition. A private registry organizes content so new birthdays can be added without duplicating the application.\n\n## Protection\n\nCredentials and sessions live in D1, and private images remain in R2. The public home page responds as not found; only intended routes expose sign-in.\n\n## Status\n\nThe project is deployed without a public demo because all content is intended for specific people.", category: "Digital experience", type: "Private web application", role: "Design, development, and operations", outcomes: ["Visual editions by person and year", "Credential-protected sessions", "Private media outside the public bundle"], seoDescription: "Private system for creating personalized birthday experiences and protecting their media." },
  { slug: "seas-venta", title: "SEAS Venta", excerpt: "Collaborative mobile app for sales, cash register, inventory, customers, and clothing-store operations.", body: "## Management from a phone\n\nSEAS Venta moves point of sale and daily store operations into Flutter: catalog, variants, customers, purchases, cash register, returns, promotions, and reports.\n\n## Offline work\n\nCatalog and customers can remain cached; sales created offline enter a local queue and synchronize when connectivity returns.\n\n## Status\n\nThis is ongoing collaborative development. Source code and data services remain private.", category: "Collaborative project", type: "Private mobile application", role: "Team product development", outcomes: ["Mobile point of sale and cash register", "Integrated inventory, customers, and reports", "Offline queue for pending sales"], seoDescription: "SEAS Venta is a private Flutter app for clothing-store sales and operations." },
  { slug: "municipalidad-de-rioja", title: "Municipality of Rioja", excerpt: "Proposal to modernize the municipality's digital presence and improve access to public information.", body: "A web concept focused on organizing municipal information and making it easier to consult across devices.", category: "Proposal archive", type: "Web proposal", role: "Interface design", outcomes: ["Information organized around public needs", "Responsive proposal"], seoDescription: "Web proposal for organizing and improving access to information from the Municipality of Rioja." },
  { slug: "discord", title: "Discord communities", excerpt: "Setup and moderation of digital spaces with understandable roles and channels.", body: "Experience organizing communities, permissions, channels, and automation to keep digital spaces clear and safe.", category: "Archive", type: "Communities", role: "Setup and moderation", outcomes: ["Clear roles and permissions", "Organized channels", "Automation for repetitive tasks"], seoDescription: "Discord community setup, permissions, moderation, and automation." },
  { slug: "nieto-hub", title: "NIETO Hub", excerpt: "Public portfolio for digital products developed for NIETO.", body: "## One shared entry point\n\nNIETO Hub brings the company's digital products together on one page, with direct access to each platform and public project profiles.\n\n## Safe, updatable content\n\nProfiles describe goals, technologies, and results without exposing repositories, credentials, or internal data. Published content is managed from Second Brain and can add projects without rebuilding the site.", category: "Client", type: "Web portfolio", role: "Design, architecture, and development", outcomes: ["NIETO products in one view", "Public detail without internal exposure", "Decoupled content ready to grow"], seoDescription: "NIETO Hub brings digital products developed for NIETO into one secure public portfolio." },
  { slug: "coffee", title: "Cafetero", excerpt: "Directory and passport for Peruvian coffee shops with maps, verifiable profiles, and visit tracking.", body: "## Problem\n\nCoffee passport information needed to become a useful directory without adding unverified reviews, ratings, or images. Every location had to preserve its source and review status.\n\n## Key decisions\n\nSearch, a map, and server-rendered profiles support public discovery. Accounts, representative requests, and moderation tasks use explicit permissions.\n\n## Process\n\nThe work organized 41 traceable coffee shops, then connected the map, profiles, visit passport, and QR codes. The public test version allows directory browsing while account and administration features are validated with real providers and devices.\n\n## Results and scope\n\nThe product includes 41 coffee shops with visible sources, SSR browsing, a map, and a personal passport. Moderation and management remain behind authorized access.", category: "Independent product", type: "Web application in testing", role: "Product, research, and development", outcomes: ["41 coffee shops with traceable sources", "Map and SSR profiles for public browsing", "Passport, visits, and permissioned management"], seoDescription: "Cafetero is a directory and passport for Peruvian coffee shops with maps, verifiable profiles, and visit tracking." },
  { slug: "explora-san-martin", title: "Explore San Martín", excerpt: "Tourism map with 164 records from official sources, verifiable content, and a personal passport.", body: "## Problem\n\nTourism information for San Martín was split across 155 MINCETUR records and nine municipal profiles. Turning it into a public map required preserving sources, flagging pending coordinates, and avoiding claims that unverified photographs were official.\n\n## Key decisions\n\nEvery profile exposes its provenance and status. Server rendering supports fast, traceable browsing; the map uses open attribution, and editorial workflows separate permissions from media.\n\n## Process\n\nSources were consolidated into a 164-place catalog, SSR profiles were prepared, and territory, search, and a personal passport were connected. D1 stores catalog and identities, R2 holds media, and MapLibre presents the map.\n\n## Results and scope\n\nExplore San Martín publishes 164 sourced places with a map and accessible profiles. Signed-in visitors can build a passport while editing stays protected.", category: "Digital tourism", type: "Web application", role: "Product, research, and development", outcomes: ["164 documented places with sources", "Accessible map and SSR profiles", "Personal passport and protected editorial workflow"], seoDescription: "Explore San Martín brings verifiable tourism locations into a public map with SSR profiles and a personal passport." },
  { slug: "ruleta", title: "Roulette", excerpt: "Local-first wheel for deciding among options, choosing several winners, and sharing editable sessions.", body: "## Decide without friction\n\nRoulette accepts pasted or edited options, weights, hidden entries, multiple winners, and repeat-or-remove behavior after a win. Selection uses Web Crypto and avoids modulo bias.\n\n## Local or shared\n\nLocal mode works without an account and offline after the first visit. Sharing saves an independent copy in D1 and provides separate participation and editing links.\n\n## Accessibility\n\nThe experience supports keyboard control, reduced motion, history, undo, and tabbed organization on small screens.", category: "Public tool", type: "Web application", role: "End-to-end design and development", outcomes: ["Uniform or weighted selection", "Offline local use", "Separate participation and editing links"], seoDescription: "Roulette helps choose among weighted options with multiple winners, offline mode, and secure sharing links." },
  { slug: "llevamos", title: "Llevamos", excerpt: "Coordinate what each person brings to a gathering without accounts or shared passwords.", body: "## Everyone brings something\n\nLlevamos organizes food, drinks, objects, and responsibilities for a gathering. The host creates the list and shares an invitation; each participant selects or proposes a contribution.\n\n## Simple, separate access\n\nEach gathering has specific links and permissions for organizing and participating. D1 stores data, and writes pass through validation, limits, and Turnstile where appropriate.\n\n## An interface for the real moment\n\nThe mobile-friendly board shows group progress and refreshes when returning to the tab or after saving, without permanent connections.", category: "Public tool", type: "Web application", role: "End-to-end design and development", outcomes: ["Coordination without accounts", "Invitation-specific permissions", "Responsive board with shared progress"], seoDescription: "Llevamos coordinates food, objects, and responsibilities for a gathering without accounts or shared passwords." },
  { slug: "horas", title: "Hours", excerpt: "Compare time zones, find overlapping work hours, and share an instant without external calls.", body: "## One instant for every city\n\nHours compares up to eight IANA zones on one timeline. The first zone defines the reference, while the system shows day changes, offsets, and daylight-saving transitions without fixed tables.\n\n## Work overlap\n\nEach zone can define its own working hours, including overnight shifts. The app calculates intersections and shares the instant, zones, and settings through a validated URL.\n\n## Privacy\n\nIntl and Luxon perform every conversion in the browser; there is no API, account, database, or analytics.", category: "Public tool", type: "Web application", role: "End-to-end design and development", outcomes: ["Comparison of up to eight zones", "Overlap for working hours", "Shareable links without stored data"], seoDescription: "Hours compares time zones, calculates working-hour overlap, and shares instants from the browser." },
  { slug: "qr", title: "QR", excerpt: "Generate, verify, and read QR codes locally with customization and safe export.", body: "## Create and check in one place\n\nQR generates codes for links, text, Wi-Fi, email, phone, SMS, contacts, calendar events, and coordinates. Colors, correction, margin, modules, and logo can be adjusted before PNG or SVG export.\n\n## Verification before download\n\nEvery rendered image is read again locally to block unreadable or ambiguous results. The reader supports files and camera through BarcodeDetector or a same-origin WebAssembly fallback.\n\n## Privacy\n\nContent lives only in memory: it is not stored in the browser, added to the URL, or sent to a server.", category: "Public tool", type: "Web application", role: "End-to-end design and development", outcomes: ["Generation for nine content types", "Local verification before export", "File or camera reading without uploads"], seoDescription: "QR generates, verifies, and reads customized codes locally without storing or sending their content." },
  { slug: "pdf", title: "PDF", excerpt: "Organize, transform, and convert PDF documents in the browser without uploading files.", body: "## A local toolkit\n\nPDF merges, splits, extracts, removes, rotates, and numbers pages. It also converts images to PDF, exports pages as PNG, and displays key document metadata.\n\n## Designed for sensitive files\n\nDocuments and filenames remain in memory. A browser Web Worker performs transformations with explicit time and size limits; there are no upload routes, databases, or remote storage.\n\n## Control and accessibility\n\nOrdering supports drag, keyboard, and range selection. Change history allows undo before download.", category: "Public tool", type: "Web application", role: "End-to-end design and development", outcomes: ["Eight organization and conversion operations", "Entirely local processing", "Accessible reordering and change history"], seoDescription: "PDF merges, splits, rotates, numbers, and converts documents locally without uploads." },
  { slug: "foto", title: "Photo", excerpt: "Compress, resize, crop, and convert image batches without taking them off the device.", body: "## A light table in the browser\n\nPhoto resizes, crops, rotates, flips, and converts JPG, PNG, and WebP files. Before-and-after comparison, presets, and batch processing support review before download.\n\n## Verifiable privacy\n\nImage bytes and filenames never leave the device. A Web Worker handles each task, removes personal metadata, and creates ZIP files locally; deletion cancels work and revokes temporary URLs.\n\n## Clear limits\n\nThe app validates signatures, dimensions, estimated memory, and actual format so errors are explained instead of producing questionable files.", category: "Public tool", type: "Web application", role: "End-to-end design and development", outcomes: ["Batch editing and conversion", "Local removal of personal metadata", "Visual comparison before download"], seoDescription: "Photo compresses, resizes, crops, and converts image batches without uploading them." },
  { slug: "cuando", title: "When", excerpt: "Polls for finding a meeting date, comparing availability, and coordinating without accounts.", body: "## Find the shared moment\n\nWhen proposes dates with time zones and records Yes, Maybe, or No. Results prioritize the greatest availability without treating a missing vote as a negative response.\n\n## Links with distinct responsibilities\n\nPublic identifiers and separate private tokens control administration and editing. Secrets travel in the URL fragment, and D1 stores only their hashes.\n\n## Complete operation\n\nOrganizers can edit, withdraw, restore, export CSV, inspect history, and permanently delete a poll with confirmation.", category: "Public tool", type: "Web application", role: "End-to-end design and development", outcomes: ["Yes, Maybe, and No availability", "Time zones with DST validation", "Separate, auditable private links"], seoDescription: "When creates availability polls with time zones and private links without requiring accounts." },
  { slug: "cotiza", title: "Cotiza", excerpt: "Create professional quotes and contract drafts with precise calculations and PDF export.", body: "## From scope to final document\n\nCotiza guides proposals through issuer, client, line items, discounts, taxes, recurring payments, milestones, and terms. A quote can also become an editable contract draft.\n\n## Local by default\n\nHistory, catalog, profile, logo, and drafts remain in the browser. Only an explicit action saves a D1 copy for sharing through separate read and edit links.\n\n## Calculations and formats\n\nDecimal.js maintains currency amounts and rounding. The app generates PDFs with embedded fonts, prints, exports JSON, and prepares a WhatsApp message for manual review.", category: "Professional tool", type: "Web application", role: "Product, design, and development", outcomes: ["Quotes and contracts in one flow", "Decimal calculations for seven currencies", "Local or consent-based shared storage"], seoDescription: "Cotiza creates professional quotes and contract drafts with precise calculations, PDF, and optional sharing." },
  { slug: "color", title: "Color", excerpt: "Color studio for converting, combining, evaluating, and exporting colors, palettes, and gradients.", body: "## A complete color lab\n\nColor combines a picker, converter, harmonies, palettes, gradients, mixing, WCAG contrast, CSS names, and reference tables. It also extracts colors from images processed locally.\n\n## Models with explicit precision\n\nCulori converts among HEX, RGB, HSL, HSV, HWB, LAB, LCH, OKLAB, OKLCH, and an approximate CMYK model. The interface distinguishes color spaces, gamut, and export limits.\n\n## No application server\n\nImages are never stored remotely; favorites, history, and palettes remain in the browser. Shared links contain only validated HEX colors.", category: "Design tool", type: "Web application", role: "End-to-end design and development", outcomes: ["Ten integrated color tools", "Conversion across perceptual and CSS spaces", "Exportable palettes and gradients without image uploads"], seoDescription: "Color is a suite for converting, combining, checking, and exporting colors, palettes, and gradients." },
];

const projectCopy = new Map(projectCopies.map((project) => [project.slug, project]));

export const FALLBACK_ENVELOPE_EN: PortfolioEnvelope = {
  ...FALLBACK_ENVELOPE,
  data: {
    site: {
      ...FALLBACK_ENVELOPE.data.site,
      headline: "I turn complex processes into clear, maintainable web products.",
      intro: "I help companies and teams design and build applications, internal systems, and digital experiences that make their work simpler.",
      availability: "Open to conversations about products, internal systems, and technical collaboration.",
      bio: "I work across product, interface, and engineering. I start by understanding the real process, reduce friction, and deliver systems people can use and maintain with confidence.",
      location: "Peru",
      seo: { title: "Arturo Vela — Digital product engineering", description: "Arturo Vela's portfolio: web applications, internal systems, automation, and interfaces built from Peru.", ogImage: "/og-card.png" },
    },
    services: [
      { id: "web-products", title: "Web products", description: "Fast, accessible applications from the core flow through deployment.", capabilities: ["React and TypeScript", "Responsive design", "Cloudflare Workers"] },
      { id: "internal-systems", title: "Internal systems", description: "Tools that organize information and replace repetitive manual processes.", capabilities: ["Data modeling", "Automation", "Integrations"] },
      { id: "ui-systems", title: "Interface systems", description: "Consistent visual languages connecting products in the same family.", capabilities: ["Chakra UI", "Semantic tokens", "Accessibility"] },
    ],
    projects: FALLBACK_ENVELOPE.data.projects.map((project) => {
      const copy = projectCopy.get(project.slug);
      if (!copy) throw new Error(`Missing English fallback for project ${project.slug}`);
      const { seoDescription, ...localized } = copy;
      return {
        ...project,
        ...localized,
        cover: project.cover ? { ...project.cover, alt: `${copy.title} project interface` } : undefined,
        gallery: project.gallery?.map((image, index) => ({ ...image, alt: `${copy.title} project screen ${index + 1}` })),
        seo: { ...project.seo, description: seoDescription },
      };
    }),
    articles: [
      {
        ...FALLBACK_ENVELOPE.data.articles[0]!, title: "Visual analysis of factors affecting rice yield", excerpt: "Exploratory reading of satellite, climate, and crop variables before predictive modeling.", body: "Understanding data comes before choosing a model. This analysis reviews distributions, relationships, and anomalies across satellite, climate, and crop variables.\n\n## What we looked for\n\n- Differences between plots and seasons.\n- Signals with a plausible relationship to yield.\n- Missing values and observations requiring review.\n- Variables that may introduce redundancy.\n\nThe result provides a more defensible basis for later modeling and documents the limits of the available evidence.", category: "Research", tags: ["Rice", "Data", "Visualization"], cover: FALLBACK_ENVELOPE.data.articles[0]!.cover ? { ...FALLBACK_ENVELOPE.data.articles[0]!.cover!, alt: "Visual analysis of agricultural and satellite data" } : undefined, seo: {},
      },
      {
        ...FALLBACK_ENVELOPE.data.articles[1]!, title: "Rice yield forecasting with satellite and climate data", excerpt: "Research process for combining temporal signals and estimating agricultural yield.", body: "Rice yield forecasting requires aligning observations from different sources and times. The proposal combines satellite indicators, climate variables, and historical yield data.\n\n## Modeling approach\n\nA Temporal Convolutional Network can learn long-range patterns without relying on a recurrent architecture. Before training, each time series must share a consistent calendar, clear missing-data rules, and evaluation splits that avoid future leakage.\n\nThe model is useful only when its error is compared with simple baselines and interpreted alongside data quality and local agronomic conditions.", category: "Research", tags: ["Rice", "Machine Learning", "Satellite data"], cover: FALLBACK_ENVELOPE.data.articles[1]!.cover ? { ...FALLBACK_ENVELOPE.data.articles[1]!.cover!, alt: "Satellite data applied to rice cultivation" } : undefined, seo: {},
      },
      {
        ...FALLBACK_ENVELOPE.data.articles[2]!, title: "Using Discord for a business or online community", excerpt: "Channels, roles, bots, and core principles for building an organized community.", body: "Discord can support service, coordination, and community for a business. The difference lies in designing a structure people understand.\n\n## A starting point\n\n- Define channels by purpose, not impulse.\n- Separate moderation and participation permissions.\n- Automate repetitive tasks with narrowly scoped bots.\n- Document rules where the community can find them.\n\nA healthy community needs more than tools: it requires clear expectations, consistent moderation, and ways to listen to members.", category: "Communities", tags: ["Discord", "Moderation", "Community"], cover: FALLBACK_ENVELOPE.data.articles[2]!.cover ? { ...FALLBACK_ENVELOPE.data.articles[2]!.cover!, alt: "An organized Discord community interface" } : undefined, seo: {},
      },
    ],
  },
};
